### ISSUE TITLE
How to avoid control process is still running

### ISSUE THREAD

**Issue by wta12** [d0vgan/nppexec#10]
Hi,
I start a NPPEXEC session as follow:
```cmd
NPP_SAVE
cd $(CURRENT_DIRECTORY) ## Which is different than TEST_FILE directory
SET TEST_FILE = "G:\PyRevitRun\Test\PyRevitTest.py"
C:\Run\IronPython.2.7.9\net45\ipyw.exe -X:Frames $(TEST_FILE)
```
It show the dialog and i must to send `QUIT()` or `EXIT()` in order to end process which also completely close notepad++ [Capature_Screen](https://drive.google.com/file/d/1-exMTevE4BTf3r5XI_hHw74uWwZ0aM6E/view?usp=sharing)
I tried to run it directly from its own folder and it run well
```cmd
NPP_SAVE
cd $(CURRENT_DIRECTORY)  # "G:\PyRevitRun\Test\"
C:\Run\IronPython.2.7.9\net45\ipyw.exe -X:Frames $(FULL_CURRENT_PATH) # "G:\PyRevitRun\Test\PyRevitTest.py"
```
both cmd and powershell console are ok 
```cmd
cmd: C:\Run\IronPython.2.7.9\net45\ipyw.exe -X:Frames -u "G:\PyRevitRun\Test\PyRevitTest.py"
ps: C:\Run\IronPython.2.7.9\net45\ipyw.exe -X:Frames -u "G:\PyRevitRun\Test\PyRevitTest.py"
```
Just wonder how to avoid this dialog to continue using NPPEXEC -  a really great stuff which mostly reliable in my daily coding
thanks

**Comment by d0vgan** [comment]
Use `set local @exit_cmd_silent = exit()` as explained in the section "4.6.4. Running Python & wxPython" of the NppExec Manual.

**Comment by d0vgan** [comment]
To get more info on this, type `help @exit_cmd` in NppExec's Console.
