### ISSUE TITLE
show and reload file content periodically

### ISSUE THREAD

**Issue by mischlrebl** [d0vgan/nppexec#101]
hello

I am wondering if it is possible to watch and track a log file in the console - like the Monitoring (tail -f) function in npp?

would be very handy to work with split screen on the files and to see the messages below.

thanks in advance

**Comment by d0vgan** [comment]
The closest built-in command in NppExec is `con_load`, though it loads an entire file into the Console window.
To achieve your goal, you may probably run some external log viewer/watcher implemented as a `console application` in NppExec's Console.

**Comment by d0vgan** [comment]
You are correct, it doesn't work in NppExec's Console. I did not check that.
The reason of why it does not work is described here, Q1:
https://d0vgan.github.io/nppexec/?q=FAQ
To sum up, in such situations you need to run a program in its own console window.

**Comment by d0vgan** [comment]
This version of `tail` seems to work in NppExec's Console:
https://github.com/JavaScriptDude/cygtail
On that page, click the "<>Code" button and then click "Download ZIP" there.
```
tail -f log.txt
```

**Comment by mischlrebl** [comment]
thanks a lot for your efforts, works like a charm! 

together with the highlighting it is a full log viewer now

**Comment by mischlrebl** [comment]
it is no rocket science...
would be for sure an interesting and real use case.
[37-0.txt](https://github.com/user-attachments/files/17751895/37-0.txt)
[37-1.txt](https://github.com/user-attachments/files/17751896/37-1.txt)
![2024-11-14 17_28_35-C__Users_ml_Streamlit_docs_readme md - Notepad++](https://github.com/user-attachments/assets/141ce656-2d64-4ba0-b90b-05c0672e7aa7)
![2024-11-14 17_29_05-C__Users_ml_Streamlit_docs_readme md - Notepad++](https://github.com/user-attachments/assets/0b6ae376-1b7f-4022-9e3c-e2413aed12db)

**Comment by d0vgan** [comment]
Wow, seeing this, it's really inspiring!
The truth is, I never thought about NppExec in terms of log viewing - but you actually transformed it into a real log viewer!

**Comment by d0vgan** [comment]
Added to the Manual:
https://d0vgan.github.io/nppexec/?q=4.6.18

**Comment by mischlrebl** [comment]
thank you for the documentation which allows everyone to set it up easily.

the wonderful tool makes it possible to implement it by no time. it has been an obvious use case in terms of npp as an ide where all necessary parts are integrated into one application.

a small hint to the highligthing: as the execution of masks is proceeded from top to bottom the presedence has to be considered. the success line in the log would also match with the lib.py case - which seems not to be applicated as there was already a match before
