### ISSUE TITLE
Can the 　exist command be implemented in the new version？

### ISSUE THREAD

**Issue by ashi876** [d0vgan/nppexec#11]
Or other convenient alternatives?

**Comment by d0vgan** [comment]
We already can use the existing constructions of e.g.
`cmd /c if exist filename command`
and
`cmd /c if exist filename ( command1 ) else ( command2)`

**Comment by d0vgan** [comment]
And here is an example of usage of an external .bat file in NppExec's script:
https://sourceforge.net/p/npp-plugins/discussion/672146/thread/b50394f7/
In this case, some advanced logic can be written inside a .bat file that will be called by NppExec.

**Comment by ashi876** [comment]
thanks

**Comment by ashi876** [comment]
> 
> 
> Or other convenient alternatives?



> 
> 
> Or other convenient alternatives?
