### ISSUE TITLE
How can I console program run time？

### ISSUE THREAD

**Issue by wkmyws** [d0vgan/nppexec#12]
For example:

set t = $(getTime)
//program
console( $(getTime) - t )

how can I implementing this function？

**Comment by d0vgan** [comment]
As mentioned in the help provided for
`help npe_console`
the following can be used:
`npe_console -- v+ m- // silent, enable the $(OUTPUT) var, no int.msgs
  cmd /c time /t       // cmd prints current time; $(OUTPUT) is set
  echo $(OUTPUT)       // NppExec prints $(OUTPUT) i.e. current time
  npe_console -- v- m+ // don't forget to disable the $(OUTPUT) var`
For additional info, refer to NppExec Manual, section "4.6.5. Grab date & time to NppExec variable".

**Comment by wkmyws** [comment]
thanks
