### ISSUE TITLE
Sending Scintilla Messages

### ISSUE THREAD

**Issue by joelmaxuel** [d0vgan/nppexec#13]
This is likely my result of not finding the right information (npp's docs subdomain is currently down and it seems all hints are pointing there), however...

I have what started as a macro:

    <Action type="3" message="1700" wParam="0" lParam="0" sParam="" />
    <Action type="3" message="1601" wParam="0" lParam="0" sParam="Test" />
    <Action type="3" message="1625" wParam="0" lParam="2" sParam="" />
    <Action type="3" message="1702" wParam="0" lParam="784" sParam="" />
    <Action type="3" message="1701" wParam="0" lParam="1615" sParam="" />

... which marks in the current NPP textfile any values with "Test", and bookmarks those lines as well.  FWIW, my real example includes a regex.

However, I do not want to hardcode the entire search term, with the rest collected from an input box or clipboard.  My understanding is that NPP's macros can do neither.

So, in trying NppExec and failing repeatedly, I have whittled the issue down to:

    set local NirCmdPath = C:\Local\App\NirCmd\nircmdc.exe
    sci_sendmsg 1700 0 0
    sci_sendmsg 1601 0 0 "Test"
    sci_sendmsg 1625 0 2
    sci_sendmsg 1702 0 784
    sci_sendmsg 1701 0 1615

... which issues no errors, but also has no effect (nothing is marked in spite of the presence of "Test" and the equivalent macro working).  I am not even sure if `sci_sendmsg` accepts a `sparam` aside from the help doc mentioning how to use strings when related to `sci_sendmsg`.

FWIW, this is a more complete version of what I was attempting (marking specific values/lines based on the second column of a pipe-delimited file):

    set local NirCmdPath = C:\Local\App\NirCmd\nircmdc.exe
    set ourQuote = "
    set ourRegex = ^(?:(?:[^\|]*\|){1})\K
    inputbox "Mark ID ..."
    sci_sendmsg 1700 0 0
    set ourCommand = sci_sendmsg 1601 0 0 $(ourQuote)$(ourRegex)$(INPUT)$(ourQuote)
    $(OurCommand)
    sci_sendmsg 1625 0 2
    sci_sendmsg 1702 0 784
    sci_sendmsg 1701 0 1615

Any suggestions?  Many thanks.

**Comment by joelmaxuel** [comment]
FWIW, I have also been trying with `npp_sendmsg` however because I need to be confident specific dialog options are chosen, my "Test" example is also hitting a brick wall.

    set local NirCmdPath = C:\Local\App\NirCmd\nircmdc.exe
    npp_sendmsg WM_COMMAND 43054 // show the Mark dialog
    npp_sendmsg NPPM_DMMGETPLUGINHWNDBYNAME " Console " "NppExec.dll"
    set local hwnd = $(MSG_RESULT)
    "$(NirCmdPath)" sendkeypress F T
    npp_sendmsgex $(hwnd) WM_COMMAND 1605 1 // Regex
    //npp_sendmsgex $(hwnd) WM_COMMAND 1616 0 1 // Bookmark
    //npp_sendmsgex $(hwnd) WM_COMMAND 1632 0 1 // In selection
    //npp_sendmsgex $(hwnd) WM_COMMAND 1604 0 0 // Match case
    //npp_sendmsgex $(hwnd) WM_COMMAND 1618 0 0 // Purge for each search
    npp_sendmsg WM_COMMAND 1615
    "$(NirCmdPath)" sendkeypress enter esc

With output:

> SET: local NirCmdPath = C:\Local\App\NirCmd\nircmdc.exe
> local $(NIRCMDPATH) = C:\Local\App\NirCmd\nircmdc.exe
> NPP_SENDMSG: WM_COMMAND 43054
> NPP_SENDMSG: NPPM_DMMGETPLUGINHWNDBYNAME " Console " "NppExec.dll"
> ; executing: NPP_SENDMSG NPPM_DMMGETPLUGINHWNDBYNAME " Console " "NppExec.dll"
> - uMsg is 0 (no message to send)
> SET: local hwnd = $(MSG_RESULT)
> local $(HWND) = 1
> "C:\Local\App\NirCmd\nircmdc.exe" sendkeypress F T
> Process started (PID=15468) >>>
> <<< Process finished (PID=15468). (Exit code 1073757860)
> NPP_SENDMSGEX: $(hwnd) WM_COMMAND 1605 1
> ; executing: NPP_SENDMSGEX $(hwnd) WM_COMMAND 1605 1
> - incorrect hWnd: should be a valid window handle
> NPP_SENDMSG: WM_COMMAND 1615
> "C:\Local\App\NirCmd\nircmdc.exe" sendkeypress enter esc
> Process started (PID=16120) >>>
> <<< Process finished (PID=16120). (Exit code 1073757860)
> ================ READY ================

Source: https://notepad-plus-plus.org/community/topic/15804/macro-delete-lines-that-contains-text-in-clipboard/6

**Comment by d0vgan** [comment]
Scintilla's messages and their parameters are explained here:
https://www.scintilla.org/ScintillaDoc.html
That document is grouped into logical sections (such as "Text retrieval and modification", "Cut, copy and paste" etc.) so it should be easy to find what you want.
The NppExec's command SCI_SENDMSG allows to pass, as well as retrieve, integer and string values to/from Scintilla. Type `help sci_sendmsg` in NppExec's Console for details.

**Comment by joelmaxuel** [comment]
Thanks, however I had already looked at both (in the case of the specific `help ...` command, I was browsing the `NppExec_HelpAll.txt` while setting up both examples until I realized the file was meant to be invoked, not read). 

Something I did not question however, is how specific this plugin is to Npp.  Early on I translated the message numbers to the constant-name equivalents until I realized they are not being understood anyway.  The specific message numbers I am attempting to use are found in:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/ScitillaComponent/FindReplaceDlg_rc.h

If this plugin targets the Scintilla messages exclusively to the Windows control, then I am not going to get a solution out of that method.

In terms of the `npp_sendmsg` method, the barrier with that is using the documented messages in the right way to set options on the dialog box (the find dialog appears and I can run the search, but I have no control[*] over the dialog options)
https://raw.githubusercontent.com/notepad-plus-plus/notepad-plus-plus/master/PowerEditor/installer/nativeLang/english.xml

I just realized that the `+` and `-` keys however, do change the options value once focus is set and they do not cycle the choice.  This may be workable now.

**Comment by joelmaxuel** [comment]
Can confirm, that I can set and unset dialog options using NirC's `sendkeypress` - assuming the value to modify has the letter 'n' as part of the `alt` hotkey, I can ...

`sendkeypress alt+n plus`

... to choose the value, with `minus` to dismiss the choice.  I did notice an option that does not reveal a hotkey when alt is held down, but it is something I don't toggle anyway (and I could still traverse it with a nearby option and then add a tab).

Closing ...
