### ISSUE TITLE
Folder as Workspace

### ISSUE THREAD

**Issue by Otaka** [d0vgan/nppexec#15]
In notepad++ there is very usefull feature - Folder as Workspace. Notepad can show file tree with root in your folder, and you can open any file in it. Usually project build files stored in root folder or in some known location relative project root, but it seems NppExec knows nothing about it, that is why I cannot reference this workspace root in my scripts.
I think it will be very good feature to have this folder in some environment variable

**Comment by d0vgan** [comment]
Looking into "PowerEditor\src\MISC\PluginsManager\Notepad_plus_msgs.h", I don't seem to find anything related to "folder", "workspace" or "project".
What is the way to retrieve the workspace path from Notepad++ ?

**Comment by d0vgan** [comment]
The community help is needed on this:
https://community.notepad-plus-plus.org/topic/18817/two-questions-about-project-panel-and-docked-windows

**Comment by d0vgan** [comment]
New variables $(WORKSPACE_ITEM_PATH), $(WORKSPACE_ITEM_ROOT) and so on are available here:
https://sourceforge.net/projects/npp-plugins/files/NppExec/NppExec Plugin v0.6 RC3-RC4 (dev)
