### ISSUE TITLE
[Enhancement] Prevent NppExec console from appending the '=== READY ===' info

### ISSUE THREAD

**Issue by pidgeon777** [d0vgan/nppexec#16]
Hi, I've tried most if not all of the NppExec console commands, but I still haven't found a way to prevent the console from appending the following string at the end of each script's execution:

`================ READY ================`

What I'd like to do is maintain the console output resulting from a previous command, without appending the string in question when each subsequent command is executed. Would that be a possible thing to do?

**Comment by d0vgan** [comment]
Currently it's not possible (i.e. the message "=== READY ===" can not be turned off).
At the level of the source code, there are 2 places responsible for this message to appear at the end of NppExec's script. Search for "================ READY ================" in the source file "NppExecCommandExecutor.cpp". Some condition can be introduced to turn it on/off. For example, it could be something similar to
```
if ( pNppExec->GetOptions().GetBool(OPTB_CONSOLE_MSGREADY) )
{
    pNppExec->GetConsole().PrintMessage( _T("================ READY ================"), false );
}
```
where `OPTB_CONSOLE_MSGREADY` needs to be added to the `enum EPluginOptions` (in NppExec.h) and the corresponding array item to be added to the `CStaticOptionsManager::OPT_ITEM optArray` (in NppExec.cpp).

**Comment by pidgeon777** [comment]
Thanks for the prompt reply. In my opinion, it would be interesting to add an option to disable the printing in the console of that string.
If someone would want to insert a marker indicating the end of an operation, he could manually add a final print to the script (echo type).
What do you think about it?

**Comment by pidgeon777** [comment]
Or, another possibility, could be to pass the option as an argument of npe_console.

E.g.:

npe_console -r =>disable ready status message
npe_console +r =>disable ready status message

**Comment by d0vgan** [comment]
This change is already in https://github.com/d0vgan/nppexec/tree/develop , please feel free to check.

**Comment by pidgeon777** [comment]
Wow, impressive. You've been really fast!

Unfortunately, Visual Studio is not installed in my system, so I have not a chance to test it...

**Comment by pidgeon777** [comment]
Ok, I've been able to build it. I'll test it right now.

**Comment by pidgeon777** [comment]
I did some tests. The console had some text:

````
AAA
BBB -> This line was highlighted in the console
CCC
````

and after having executed this script:

````
npp_console disable
npe_console a+ --
npe_console p- --

npp_menucommand Plugins||NppExecSearch||Toggle ConsoleSearch
npp_menucommand Plugins||NppExecSearch||Go to next error
````

then the console cursor went to the last row of the console.

Is there a way to prevent this behaviour, so that the cursor position in the console is not touched after executing a script?

**Comment by d0vgan** [comment]
To achieve that, I'd have to make a lot of changes - such as verifying whether something was printed to the Console or not inside each internal command. Well, maybe it could be solved in some less complicated way, but anyway there's no ready-to-use mechanism for this, and a noticeable effort would be needed to create one.

**Comment by pidgeon777** [comment]
Ok thanks for the detailed analysis. Maybe something like this could be more achievable?:

https://github.com/d0vgan/nppexec/issues/17

This is what I was trying to implement in my 'Console error browsing' script.

**Comment by d0vgan** [comment]
The latest NppExec.dll built from the development branch (i.e. a work-in-progress version, not a final release!) is available here:
https://sourceforge.net/projects/npp-plugins/files/NppExec/NppExec%20Plugin%20v0.6%20RC3-RC4%20%28dev%29/

**Comment by pidgeon777** [comment]
Hello, what feature was added in the release you mentioned above? I'm not sure if it is related to the one I described in this topic or not.

**Comment by d0vgan** [comment]
The added feature is this one:
`the message "==== READY ====" is optional now (npe_console p-)`
