### ISSUE TITLE
[Enhancement] Better handling of error navigation in case of multiple NppExec consoles

### ISSUE THREAD

**Issue by pidgeon777** [d0vgan/nppexec#17]
Let's suppose a situation as follows:

- ConsoleA active and shown
- ConsoleB active but hidden in the panels stack

- HotkeyA: display next/previous error for ConsoleA
- HotkeyB: display next/previous error for ConsoleB

If I press HotkeyB, then I can actually navigate the errors in the code, but ConsoleB stays hidden. It would be cool to automatically show ConsoleB when activating HotkeyB. Then, once ConsoleB is active, activating HotkeyA should lead to displaying ConsoleA.

**Comment by d0vgan** [comment]
Looks like it's not straightforward. The community help is needed:
https://community.notepad-plus-plus.org/topic/18817/two-questions-about-project-panel-and-docked-windows

**Comment by pidgeon777** [comment]
Thank you for investigating the problem.

If only there was a means to bring this feature into being, I feel confident it would greatly streamline and quicken error navigation across a multitude of active consoles.

**Comment by d0vgan** [comment]
Should be fixed in NppExec v0.6 RC4:
https://github.com/d0vgan/nppexec/releases/tag/v06-RC4

**Comment by pidgeon777** [comment]
Out of curiosity, does the v0.6 RC4 release also include this fix?:

https://github.com/d0vgan/nppexec/issues/24

**Comment by d0vgan** [comment]
v0.6 RC4 does not include the fix for #24 because this fix is implemented after the RC4 had been released.

**Comment by pidgeon777** [comment]
> Should be fixed in NppExec v0.6 RC4:
> https://github.com/d0vgan/nppexec/releases/tag/v06-RC4

Tested and work great!
