### ISSUE TITLE
[Enhancement] NppExec error browsing on secondary view

### ISSUE THREAD

**Issue by pidgeon777** [d0vgan/nppexec#18]
Actually, when browsing for errors listed in the NppExec console output, these are shown in the primary view by default.

I think an option should be added so that when activating one of the listed errors, then a secondary view appears pointing to the same line as reported by the error. Moreover, clicking on each of those errors should still open the related files to the second view, without touching the primary one. If a document is already opened in the primary view, it should then be cloned into the secondary one.

Why this could be useful?

I created a script which shows me the definition of a function given its name. It would be cool to still maintain the focus on the current document I'm currently editing in the first view, while opening these found definition in the secondary view. So, this enhancement would really improve focus.

**Comment by pidgeon777** [comment]
In the meanwhile another temporary option could be this one: when browsing for errors in the NppExec console, the code navigation should occur in the focused view.

At the moment the behaviour is as follows:

1) I activate view A.
2) I execute a NppExec command.
3) I activate view B.
4) I navigate through NppExec console errors.
5) View A is updated pointing to the error's line.

It would be nice to add an option so that the currently active view gets updated instead, and not the one on which the NppExec command was executed at first.

**Comment by d0vgan** [comment]
Please try the latest sources from
https://github.com/d0vgan/nppexec/tree/develop

**Comment by pidgeon777** [comment]
Hello, which one did you implement among the suggestions I reported above?

Anyway, I'm encountering some issues while testing your modification. My first setup is as follows:

- ConsoleA active.
- ShortcutA to navigate ConsoleA errors.
- Only one view active (the primary one).

I activate ShortcutA, and error navigation occurs in the only active view. Should I expect the secondary view to open instead (my first post)?

The second test setup is as follows:

- ConsoleA active.
- ConsoleB active.
- ShortcutA to navigate ConsoleA errors.
- ShortcutB to navigate ConsoleB errors.
- Primary and secondary views active.

1) I execute a ConsoleA command with the primary view active.
2) I activate focus on the secondary view.
3) I execute ShortcutA.
4) Error navigation occurs on the primary view.

Should I expect error navigation to occur on the secondary view (which was the active one), according to the suggestion in my second post?

Thanks again.

**Comment by pidgeon777** [comment]
I forgot one detail, during the tests the documents that may be opened through the error navigation, were already all loaded in the Notepad++ session.

So, could this simply mean that for each item on the error list of the console, the view hosting the already opened document was automatically displayed? Which of course could be the primary or secondary view...

**Comment by d0vgan** [comment]
What I did was the following:
1) If a file is present in the Secondary View, and the Secondary View is active, the double-click activates the file in the Secondary View.
2) If a file is present only in the Secondary View, and the Primary View is active, the double-click activates the file in the Secondary View (because there's no such file in the Primary View). This corresponds to the default behavior of Notepad++.
3) If a file is not present neither in the Primary nor in the Secondary View, the file is opened in the Primary View. This is the default behavior of Notepad++.

**Comment by pidgeon777** [comment]
Ok thanks for the explanation, so I wonder what was the previous behaviour of your plugin in the three situations you listed.

Also, I would like to ask if with Notepad++ there is the chance to display the same file on both views.
