### ISSUE TITLE
Better folder organization.

### ISSUE THREAD

**Issue by SalviaSage** [d0vgan/nppexec#2]
Hello, 

I noticed that the doc folder doesn't have a folder of its own, it should be doc\NppExec

This is how it is with PythonScript, it has its own documentation folder in the doc folder in the np++ directory.

I would like to see this implemented please.

Also, I noticed that there is a seperate NppExec folder here with 4 different .h files. Where do these files go? I simply copy pasted the whole folder into the plugins folder, the .dll was copy pasted into the same folder too. Please confirm this is the correct way to install it.

I just want users to have an easier time with their installations, for this reason I would like to ask you to include something like a readme file. 

Maybe even make something like an installer! (if you can)

thanks for putting the project on github, looking forward to next releases!

**Comment by d0vgan** [comment]
Done in NppExec v0.6 RC1.
