### ISSUE TITLE
Works only if file has no spaces

### ISSUE THREAD

**Issue by LorneCash** [d0vgan/nppexec#23]
*Forgive me if this isn't the right place for this

This command works if the file path/name does not contain spaces but it fails if spaces exist.

_NPP_RUN PowerShell start-process PowerShell -ArgumentList '-ExecutionPolicy Unrestricted -File "$(FULL_CURRENT_PATH)"'_

The reason I think this might be a bug is that the command works fine from powershell with or without spaces in the file path/name.

If I'm wrong and this isn't a bug and there is a way to make it work with spaces please share.

**Here's my complete script:**
_NPP_CONSOLE ?
NPP_SAVE
IF $(EXT_PART) = .ps1
	NPP_RUN PowerShell start-process PowerShell -ArgumentList '-ExecutionPolicy Unrestricted -File "$(FULL_CURRENT_PATH)"'
ELSE IF $(EXT_PART) = .bat
	NPP_RUN cmd /C "$(FULL_CURRENT_PATH)"
ELSE IF $(EXT_PART) = .cmd
	NPP_RUN cmd /C "$(FULL_CURRENT_PATH)"
ELSE
	MESSAGEBOX "File type has not been configured in NppExec's 'Run' script" : "NppExec: Run - Unknown File Type" : 1
ENDIF_

**Comment by d0vgan** [comment]
I don't really like PowerShit, especially for its unusual syntax. And when I try to run you example, this is what PowerShell tells me:

`Could not find a positional parameter that accepts an argument "PowerShell".
+ start-process <<<<  PowerShell -ArgumentList -ExecutionPolicy Unrestricted -File C:\Progs\Notepad++\Hello World
.ps1
    + CategoryInfo          : InvalidArgument: (:) [Start-Process], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.StartProcessCommand`

So it looks like PowerShell expects some different arguments. You better ask PowerShell's gurus about it, since it's up to PowerShell's syntax.

**Comment by LorneCash** [comment]
I'm sorry but you are incorrect.  You're missing the single quotes in your string.

[Here's proof](https://www.dropbox.com/s/x0c0go2g8gmbmpm/Powershell%20Example.png?dl=0)

**Comment by d0vgan** [comment]
Well, I think I've managed to get it to work:
`NPP_RUN PowerShell -Command start-process PowerShell -ArgumentList '-ExecutionPolicy Unrestricted -File \"$(FULL_CURRENT_PATH)\"'`
Looks like the double quotes simply disappear when they are passed to the second instance of PowerShell if they were not escaped with '\\'.

**Comment by LorneCash** [comment]
Wow! I swear I tried that. I thought I tried every escape character option I could think of... not sure how I messed that up.

I think now you just need to update the help document
**4.6.7. Run and terminate PowerShell process**
Seems really complicated compared to this. (see below)

### A few other options that work:
**ExecutionPolicy is likely need it both places (not tested)**
`NPP_RUN PowerShell -ExecutionPolicy Unrestricted start-process PowerShell -ArgumentList '-ExecutionPolicy Unrestricted -File \"$(FULL_CURRENT_PATH)\"'`

**Using a string array for -ArgumentList**
`NPP_RUN PowerShell start-process PowerShell -ArgumentList @('-ExecutionPolicy Unrestricted', '-File \"$(FULL_CURRENT_PATH)\"')`

**Shortest possible (Using PowerShell to start PowerShell)**
`NPP_RUN PowerShell start-process PowerShell '-File \"$(FULL_CURRENT_PATH)\"'`

**Shortest possible (I'm currently using this)**
`NPP_RUN cmd /c start PowerShell -file "$(FULL_CURRENT_PATH)"`

**Comment by d0vgan** [comment]
OK! Looks like here is the version that works under all circumstances and does not have an extra blinking console window:
`cmd /c echo. | PowerShell -ExecutionPolicy Unrestricted start-process PowerShell -ArgumentList '-ExecutionPolicy Unrestricted -File \"$(FULL_CURRENT_PATH)\"'`
Notice this one does not need NPP_RUN in the beginning since the combination of "cmd /c echo. | PowerShell" starts and ends the PowerShell process using NppExec's Console.

**Comment by d0vgan** [comment]
This works for an embedded command:
`cmd /c echo. | PowerShell -Command Write-Host 'Hello, World!'`

**Comment by LorneCash** [comment]
Glad I can contribute!!
I've achieved my goal and I'd like to submit this for your consideration/use.  Feel free to include in your documentation if you want to add a footnote giving me credit that would be great but not required)

So what happens when I'm debugging PowerShell or batch scripts is I run them a lot with pauses in them but I have to manually close them out after a while because there the paused windows stack up after a while and I'm too lazy to close them every time I run a test.  This script solves that problem by saving the PID if the last run and closing it (gracefully, not with an end task but that would work too) if it's still running before starting the next run.  I have one reservation and that is because of my ignorance as to how PID's are assigned... if I did actually close the window manually or if there were no pause to stop if from closing automatically, It may be technically possible that the same PID would get assigned to another process and potentially this script could kill that process but I'm assuming that's not an issue and that the OS doesn't assign the same PIDs in the same session or something like that.  Anyways, code is below and I hope someone else out there finds this useful too.

NPP_CONSOLE ?
NPP_SAVE
PowerShell -command "get-process -Id $(PS_ID) -ErrorAction SilentlyContinue | ForEach-Object {$null = $_.CloseMainWindow()};"
IF $(EXT_PART) = .ps1
	NPE_CONSOLE v+
	PowerShell -command "(start-process -PassThru PowerShell -ArgumentList '-file ""$(FULL_CURRENT_PATH)""').Id"
	SET PS_ID = $(OUTPUT)
	NPE_CONSOLE v-
ELSE IF $(EXT_PART) = .bat
	NPE_CONSOLE v+
	PowerShell -command "(start-process -PassThru cmd -ArgumentList '/c ""$(FULL_CURRENT_PATH)""').Id"
	SET PS_ID = $(OUTPUT)
	NPE_CONSOLE v-
ELSE IF $(EXT_PART) = .cmd
	NPE_CONSOLE v+
	PowerShell -command "(start-process -PassThru cmd -ArgumentList '/c ""$(FULL_CURRENT_PATH)""').Id"
	SET PS_ID = $(OUTPUT)
	NPE_CONSOLE v-
ELSE
	MESSAGEBOX "File type has not been configured in NppExec's 'Run' script" : "NppExec: Run - Unknown File Type" : 1
ENDIF

**Comment by d0vgan** [comment]
Well, yes, I think I'll add this version for reference:
```
npp_console ?  // don't show the Console if it's hidden
npp_save       // save the current file
if "$(PS_ID)" != "" then
  // closing the previous running process by its id...
  cmd /C echo. | PowerShell -Command "get-process -Id $(PS_ID) -ErrorAction SilentlyContinue | ForEach-Object {$null = $_.CloseMainWindow()};"
endif
// is it a batch file?..
set local IS_BATCH_FILE = false
if "$(EXT_PART)" ~= ".bat" then
  set local IS_BATCH_FILE = true
else if "$(EXT_PART)" ~= ".cmd" then
  set local IS_BATCH_FILE = true
endif
// running a new process and saving its id...
npe_console v+ --
if "$(IS_BATCH_FILE)" == "true" then
  cmd /C echo. | PowerShell -Command "(start-process -PassThru cmd -ArgumentList '/c ""$(FULL_CURRENT_PATH)""').Id"
  set PS_ID = $(OUTPUT)
else if "$(EXT_PART)" ~= ".ps1" then
  cmd /C echo. | PowerShell -ExecutionPolicy Unrestricted -Command "(start-process -PassThru PowerShell -ArgumentList '-File ""$(FULL_CURRENT_PATH)""').Id"
  set PS_ID = $(OUTPUT)
else
  messagebox "File type has not been configured in NppExec's 'Run' script" : "NppExec: Run - Unknown File Type" : warn
endif
npe_console v- --
```

**Comment by LorneCash** [comment]
Yea that's a bit more refined...

Why do you add the "cmd /C echo." in front of the PowerShell commands?  I saw your other comment about the embedded command but what do you mean by that or is there a better explanation?  It seems like PowerShell works fine embedded too, no? My understanding of embedded is just that you don't have to put "npp_run" in front of the command.  In addition why have the "echo." why output an empty line that no one will see?

**Comment by d0vgan** [comment]
Hmm, does it mean that the PowerShell process correctly finishes for you when you run it without the leading `cmd /C echo. |` ?
Because for me, if I specify just `PowerShell ...` then it does its job and then waits forever until I kill its process. I.e. in order to finish the PowerShell process normally, I have to specify this leading `cmd /C echo. |` - otherwise here is what I seeing:
```
PowerShell -ExecutionPolicy Unrestricted -Command "(start-process -PassThru PowerShell -ArgumentList '-File ""C:\Progs\Notepad++\Hello World.ps1""').Id"
Process started (PID=6116) >>>
1208
```
and this process seems to wait for something and it _never_ finishes!
Whereas with the leading `cmd /C echo. |` I see
```
cmd /C echo. | PowerShell -ExecutionPolicy Unrestricted -Command "(start-process -PassThru PowerShell -ArgumentList '-File ""C:\Progs\Notepad++\Hello World.ps1""').Id"
Process started (PID=1144) >>>
6700
<<< Process finished (PID=1144). (Exit code 0)
```
i.e. the PowerShell process finishes correctly.

**Comment by d0vgan** [comment]
And I observe this behavior under Windows 7 (64-bit), Windows 8.1 (64-bit) and Windows 10 (64-bit).

**Comment by LorneCash** [comment]
PowerShell -command should be equivalent to cmd /c

Strange... I'm on Windows 10 x64 and mine works fine.  There's a setting **Replace Command Prompt with Windows PowerShell in the menu...** I wonder if it does more than just the menus

[PowerShell is replacing Command Prompt](https://support.microsoft.com/en-us/help/4027690/windows-powershell-is-replacing-command-prompt)

**Comment by LorneCash** [comment]
Did you get yours to work without cmd yet?
Also the script you posted above... you only have " -ExecutionPolicy Unrestricted" in 1 of 4 places.  I'm thinking you should remove it from all places and add a separate note that you may want to add it if you don't wanna change your policy but including it everywhere would be another option I just feel it should be consistent.

**Comment by d0vgan** [comment]
OK, I've updated the Manual once again :)
And no, it's not OK for me without cmd. But I did not do any intergation of PowerShell into command prompt since I use PowerShell very-very-very rarely.

**Comment by LorneCash** [comment]
Overall my mistake there is no issue with spaces but good outcome and useful code for everyone created in the process.
