### ISSUE TITLE
[Enhancement] Auto expand editor code tree when navigating through clickable NppExec console lines

### ISSUE THREAD

**Issue by pidgeon777** [d0vgan/nppexec#24]
Let's suppose a clickable line is reported in NppExec console window.

If this line belongs to a collapsed section of code opened in Notepad++, then by activating it through the console, the editor cursor disappears as if it was placed inside the collapsed section of code, and no expanded line is shown in the editor.

It would be a good idea to add an option so that when a clickable line is reported in the NppExec console window, clicking on it would automatically expand the associated line code if collapsed, by finally placing the cursor in the proper line/column position.

**Comment by d0vgan** [comment]
Please try NppExec20201008 from https://sourceforge.net/projects/npp-plugins/files/NppExec/NppExec%20Plugin%20v0.6%20RC3-RC4%20%28dev%29/

**Comment by pidgeon777** [comment]
Works great so far!

**Comment by d0vgan** [comment]
Included in NppExec v0.6.1.
