### ISSUE TITLE
[Bug] Can't detect paths which include '%20' strings

### ISSUE THREAD

**Issue by pidgeon777** [d0vgan/nppexec#26]
I'm running a check against an XML file through NppExec. My console output filter is configured as follows::

`set Red1 = file:///%ABSFILE%:%LINE%.*`

This is the generated command output:

![image](https://user-images.githubusercontent.com/13739892/99822518-9c549180-2b53-11eb-8ccd-e6e619c7e8f8.png)

The issue is due to the fact that error navigation doesn't work supposedly because the path includes the '%20' substrings, thus it is not recognized:

![image](https://user-images.githubusercontent.com/13739892/99822539-9fe81880-2b53-11eb-804c-84d6ae01fdba.png)

**Comment by d0vgan** [comment]
I don't see an error in the error navigation here because "%20" is definitely not the same as " ". Let's imagine another language that would use e.g. "$20" instead of " " and so on...
To deal with this case, you could use NppExec's Replacing Filter, specifying to replace "%20" with " ".

**Comment by pidgeon777** [comment]
I thought the %ABSFILE% parser already took into account the presence of those '%20', but yes, in this case then it shouldn't be classified as a bug. I didn't think of the replacing filters.

I've got a further question: let's suppose I would like to dynamically enable the global 'Enable Replacing Filter', during script execution:

![image](https://user-images.githubusercontent.com/13739892/99846874-6cb78080-2b77-11eb-83dc-f8fd6cbbe832.png)

Would it be possible to do this?

**Comment by d0vgan** [comment]
> I would like to dynamically enable the global 'Enable Replacing Filter', during script execution
```
npe_console r+ --
```
type `help npe_console` for more details.
And `help con_filter` shows examples with dynamic values of the Replacing Filters (see the Remarks section).
Also, I believe that enabling any filter via `con_filter` automatically enables the global checkbox (either it is "Enable Console Output Filter" or "Enable Replacing Filters").

**Comment by pidgeon777** [comment]
Will test it. Thank you!
