### ISSUE TITLE
Scintilla Annotations

### ISSUE THREAD

**Issue by TM4889** [d0vgan/nppexec#30]
Scintilla Documentation
[https://www.scintilla.org/ScintillaDoc.html#Annotations](url)

SCI_ANNOTATIONSETTEXT(line line, const char *text)
An annotation may consist of multiple lines separated by '\n'.

A want to add an annotation with multiple lines. The documentation says this works with '\n'. When i use this with 'sci_sendmsg SCI_ANNOTATIONSETTEXT' it doesn't work. It writes the '\n' as chars to the annotation.

**Comment by d0vgan** [comment]
It's not specific to SCI_ANNOTATIONSETTEXT, it's a general way of dealing with strings. Consider e.g. the following file path: "C:\new_folder\new_subfolder\new_file.txt" - are you expecting all the "\n" to be new lines here, in general?
The source files in C, C++, C# and other programming languages support so-called escaped string literals where "\n" is treated as a new line symbol, "\t" is treated as a TAB character and so on when they are present in a string within you source file. In fact, the compiler replaces all "\n" with a hex code 0x0A, all "\t" with a hex code 0x09 and so on while it compiles your source files.
NppExec is not a compiler and it does not support escaped string literals by default.
To have a new line symbol in a string in NppExec, one could do e.g. the following:
```
set local s ~ strfromhex "line 1" 0A 00 "line 2"  // 0A 00 is a new line here
set local line = 1
sci_sendmsg SCI_ANNOTATIONSETTEXT $(line) "$(s)"  // notice quotes around the string variable
```
