### ISSUE TITLE
Use of $(CURRENT_LINE) and  $(CURRENT_COLUMN)

### ISSUE THREAD

**Issue by Gitoffthelawn** [d0vgan/nppexec#33]
NppExec allows accessing:

````
$(CURRENT_LINE)  :  current line number
$(CURRENT_COLUMN)  :  current column number
````

Where can these be used?

I'm trying to copy all text in the current tab to a new tab without changing the position of the cursor in the current tab.

To do this, I created a regular macro that presses Ctrl+A and then Ctrl+C, then creates a new tab, and finally presses Ctrl+V.

I then created an NppExec script to store $(CURRENT_LINE) and $(CURRENT_COLUMN) and call that macro.  Within the macro, I want to restore the current cursor position before creating the new tab.  That way, when I choose to return to the original tab, the cursor will be at the correct position.

How can this be accomplished?

**Comment by d0vgan** [comment]
I'd suggest to deal directly with Scintilla since all the text operations are handled by it.
Regarding selection, refer to https://www.scintilla.org/ScintillaDoc.html#SelectionAndInformation .
The following NppExecs script snippets can be used to deal with selection:
```
// saving the caret pos & anchor
sci_sendmsg SCI_GETCURRENTPOS
set local pos = $(MSG_RESULT)
sci_sendmsg SCI_GETANCHOR
set local anchor = $(MSG_RESULT)

// selecting all
sci_sendmsg SCI_SELECTALL
sleep 1000 // to observe the selection changed

// restoring the caret pos & anchor
sci_sendmsg SCI_SETSEL $(anchor) $(pos)
```

Also, looking at https://www.scintilla.org/ScintillaDoc.html#CutCopyAndPaste , we may end up with the following NppExec script:
```
// saving the caret pos & anchor
sci_sendmsg SCI_GETCURRENTPOS
set local pos = $(MSG_RESULT)
sci_sendmsg SCI_GETANCHOR
set local anchor = $(MSG_RESULT)

// selecting all
sci_sendmsg SCI_SELECTALL

// copying the selection to the clipboard
sci_sendmsg SCI_COPY

// restoring the caret pos & anchor
sci_sendmsg SCI_SETSEL $(anchor) $(pos)

// open new editor pane
NPP_SENDMSG WM_COMMAND IDM_FILE_NEW

// pasting the text from the clipboard
sci_sendmsg SCI_PASTE
```

Inspecting the Scintilla's documentation further, we can notice `SCI_COPYRANGE` that allows to simplify the whole script:

```
// getting the length of the document
sci_sendmsg SCI_GETTEXTLENGTH
set local textlength = $(MSG_RESULT)

// copying the whole text to the clipboard
sci_sendmsg SCI_COPYRANGE 0 $(textlength)

// open new editor pane
NPP_SENDMSG WM_COMMAND IDM_FILE_NEW

// pasting the text from the clipboard
sci_sendmsg SCI_PASTE
```

**Comment by d0vgan** [comment]
Here is an advanced version that:
- applies the encoding of the original document to the new one
- sets the same positions of the caret+anchor as in the original document

In fact, I've just learnt a few new things here. This script may be a good candidate to be included in the next version of NppExec Manual :)

```
// getting the current buffer id
npp_sendmsg NPPM_GETCURRENTBUFFERID
set local $(originalBufferId)= $(MSG_RESULT)

// getting the current buffer encoding
npp_sendmsg NPPM_GETBUFFERENCODING $(originalBufferId)
set local bufEnc = $(MSG_RESULT)

// getting the caret pos & anchor
sci_sendmsg SCI_GETCURRENTPOS
set local pos = $(MSG_RESULT)
sci_sendmsg SCI_GETANCHOR
set local anchor = $(MSG_RESULT)
sci_sendmsg SCI_GETFIRSTVISIBLELINE
set local firstvisibleline = $(MSG_RESULT)

// getting the length of the document
sci_sendmsg SCI_GETTEXTLENGTH
set local textlength = $(MSG_RESULT)

// copying the whole text to the clipboard
sci_sendmsg SCI_COPYRANGE 0 $(textlength)

// open new editor pane (new document)
NPP_SENDMSG WM_COMMAND IDM_FILE_NEW

// getting the new buffer id
npp_sendmsg NPPM_GETCURRENTBUFFERID
set local newBufferId = $(MSG_RESULT)

// setting the new buffer encoding
npp_sendmsg NPPM_SETBUFFERENCODING $(newBufferId) $(bufEnc)

// pasting the text from the clipboard
sci_sendmsg SCI_PASTE

// setting the caret pos & anchor
sci_sendmsg SCI_SETSEL $(anchor) $(pos)
sci_sendmsg SCI_SETFIRSTVISIBLELINE $(firstvisibleline)

```

**Comment by Gitoffthelawn** [comment]
Wow! Thank you!  There's a lot for me to learn in what you generously provided, so I'll need a little time to digest everything and try it all out.  It looks very promising.  Thank you very much, and I'm glad you were able to learn some new things as well!

**Comment by Gitoffthelawn** [comment]
This really looks great, and I've gone through it and it all makes good sense.  Many thanks again.

I have a little spare time, and I'm going to give it all a try and work to integrate it into my project.

I'm still curious, what are the possible uses for `$(CURRENT_LINE)` and `$(CURRENT_COLUMN)`?

**Comment by d0vgan** [comment]
As for `$(CURRENT_LINE)`, it for example can be used to get the text of the current line according to
 https://www.scintilla.org/ScintillaDoc.html#SCI_GETLINE
```
sci_sendmsg SCI_GETLINE $(CURRENT_LINE) @""
echo $(MSG_LPARAM)
```
As for `$(CURRENT_COLUMN)`, I am not very sure where exactly to use it. What comes to my mind immediately, though, is the form of compiler output where it reports some error in the source code. We can produce similar message, though I don't know for what purpose:
```
echo Error in file '$(FILE_NAME)' on line $(CURRENT_LINE) pos $(CURRENT_COLUMN)
```

**Comment by Gitoffthelawn** [comment]
Thank you.  Very helpful info.  I thought perhaps there was an intended use directly with one of the unique commands provided by NppExec, but it sounds like that ephemeral hypothesis was not correct. :)

**Comment by d0vgan** [comment]
The script examples above have been added to the NppExec Manual:
https://github.com/d0vgan/nppexec/commit/4511b7a6c893c0c08c6b947548a76a5417e17632

**Comment by Gitoffthelawn** [comment]
Great! Thanks!
