### ISSUE TITLE
FR: Allow messagebox to show a message box that times out after x ms

### ISSUE THREAD

**Issue by Gitoffthelawn** [d0vgan/nppexec#36]
It would be great to enhance `messagebox "text" : "title"`  to allow showing a message box with a custom title and have a timeout (close itself) after `x` ms.  This way, the user won't be forced to always interact with the message box.

Thanks again for NppExec!

**Comment by d0vgan** [comment]
This might be implemented using the technique mentioned here:
https://stackoverflow.com/questions/3091300/messagebox-with-timeout-or-closing-a-messagebox-from-another-thread
Actually it is described here:
https://www.codeproject.com/Articles/7914/MessageBoxTimeout-API
I'll think about it.

**Comment by Gitoffthelawn** [comment]
Thanks! Here are 2 additional techniques that maybe could help you implement this functionality.  I'm not sure, so I'll just mention them briefly:

1. Use a system notification.
2. Do something like PowerShell does.  Foe example, in PowerShell, `Shell.Popup("d0vgan", 1, "Title", 4096);` will display a popup with the title `Title` and your username in the body.  It will then close itself after 1 second if the user doesn't click on the `OK` button.

**Comment by d0vgan** [comment]
https://github.com/d0vgan/nppexec/commit/9b81be628028f9709931413b04dff36bc6fa9e4e

**Comment by Gitoffthelawn** [comment]
Wonderful! Thanks! You wouldn't believe the workaround I've been using... I actually have been using nppExec to push data to another application that then displays a notification (using the pushed data) that times out after 750ms.  LOL.

It will be great to have this native within nppExec, and I look forward to deleting my workaround.

**Comment by d0vgan** [comment]
https://community.notepad-plus-plus.org/topic/21365/nppexec-latest-development-version

**Comment by d0vgan** [comment]
https://github.com/d0vgan/nppexec/releases/tag/v07

**Comment by Gitoffthelawn** [comment]
Thank you very much!
