### ISSUE TITLE
add Fluent icon for toolbar

### ISSUE THREAD

**Issue by pryrt** [d0vgan/nppexec#39]
As of Notepad++ v8.0, plugin authors need to call NPPM_ADDTOOLBARICON_FORDARKMODE instead of NPPM_ADDTOOLBARICON.  (It could be done in an "if", because you can read the NPP version from a plugin; but also, I don't think it hurts to call both messages, so just running both all the time should work as well... though I'm not a plugin developer, so it would be best to confirm that)

**Comment by pryrt** [comment]
So, per [my post](https://community.notepad-plus-plus.org/post/66886) in the forum, here are my attempts.

* [NppExec-ConsoleIcon-whitescreen.zip](https://github.com/d0vgan/nppexec/files/6620135/NppExec-ConsoleIcon-whitescreen.zip) => this is your original console icon, in a few different sizes = original 16x16, 14x14 cropped, 14x14 "bigger" (resized so there's no transparency outline, so less chance of black lines on docking panel), 32x32, and multisize (a single icon file with 32x32, 16x16, and 14x14
* [NppExec-ConsoleIcon-blackscreenscreen.zip](https://github.com/d0vgan/nppexec/files/6620133/NppExec-ConsoleIcon-blackscreenscreen.zip) => this took the "screen" portion of your original icon and inverted the colors (so a black screen) = same sizes at whitescreen versions
* [NppExec-ConsoleIcon-FluentUI.zip](https://github.com/d0vgan/nppexec/files/6620134/NppExec-ConsoleIcon-FluentUI.zip) => this is derived from one of NPP's FluentUI Icons = each file has two sizes (32x32 and 16x16)

My recommendations for combinations to try:
* bmp = your original bmp; ToolbarIcon = multisize white; ToolbarIconDarkMode = multisize black; docking icon = try either the same multisize white, or try each of the individual 14x14 icons one at a time
* bmp = original; ToolbarIcon = white 16x16; ToolbarIconDarkMode = black 16x16; docking icon = one of the 14x14
* bmp = original; ToolbarIcon = FluentUI; ToolbarIconDarkMode = FluentUI Filled; docking icon = one of the 14x14

You are under no obligation to actually use these.  You are under no obligation to credit me (I mostly derived them from your icon and one of Don's icons, so they're not exactly original-to-me works).

Hopefully this will be helpful

**Comment by d0vgan** [comment]
The multisize icons seem to work better (especially with large toolbar icons):
https://github.com/d0vgan/nppexec/commit/a95a7369e4a311fbc4486df2a9627a87ad8e65cc

**Comment by d0vgan** [comment]
https://community.notepad-plus-plus.org/topic/21365/nppexec-latest-development-version

**Comment by pryrt** [comment]
Looks good to me.  

I'll let you decide whether to close this issue now, or only after you've made the permanent rather than development release.

**Comment by d0vgan** [comment]
https://github.com/d0vgan/nppexec/releases/tag/v07
