### ISSUE TITLE
modify selected text and save to file

### ISSUE THREAD

**Issue by econwang** [d0vgan/nppexec#4]
I know that `sel_saveto` will save the selected text to target file, but how to modify the selected text such as add one blank line then save to target file?

**Comment by d0vgan** [comment]
I'd say the correct answer is to change the order of these operations:
1. save the selected text via sel_saveto;
2. modify the saved file by some external tool.
For example, sfk (Swiss File Knife) supports a lot of ways to modify a file, and, moreover, it supports commands chaining (i.e. it's possible to apply one modification, then apply another one to the result and so on), plus now it does support UTF-8 and UCS-2 files. So I'd recommend to try to use sfk for any additional file modifications.

**Comment by d0vgan** [comment]
Got a response from sfk's developer of how to append/insert text lines by means of sfk:
1. To append several lines similar to
```
cmd /c echo trailing line1>>myfile.txt
cmd /c echo trailing line2>>myfile.txt
```
use the following:
```
sfk echo -spat "trailing line1\ntrailing line2" +append myfile.txt
```

2. Example to insert some text before line 5:
```
sfk filt -lnum in.txt +xed "/[lstart]005 /005 text to insert\n[all]/" +xed "/[lstart]* //"
```

3. Example to insert after a specific string (e.g. insert after a line that contains a string "insert something after me"):
```
sfk xed in.txt "/[lstart]*insert something after me*[eol]/[all]the new text\n/"
```

**Comment by econwang** [comment]
Thanks, previously we use something similar, but want a Notepad++ build in command to handle, is there any SCI command can do this? since we can call SCI command in NPPExec.

**Comment by d0vgan** [comment]
It's possible to append a string, for example, in the following way:
```
set local str ~ strfromhex 0D 00 0A 00 "Some string" // first 4 bytes are \r\n
sci_sendmsg SCI_GETCODEPAGE
set local sci_cp = $(MSG_RESULT)
if $(sci_cp) == 65001 // UTF-8
  set local str_len ~ strlenutf8 $(str)
else
  set local str_len ~ strlen $(str)
endif
sci_sendmsg SCI_APPENDTEXT $(str_len) "$(str)" // append a string
text_saveto $(SYS.TEMP)\out.txt // save to the output file
sci_sendmsg SCI_UNDO // undo
```
Probably it looks too advanced. Anyway, I think this example is worth to be added to the NppExec Manual :)

**Comment by d0vgan** [comment]
NppExec v0.6 RC2 (a version being developed currently) will allow to replace
```
sci_sendmsg SCI_GETCODEPAGE
set local sci_cp = $(MSG_RESULT)
if $(sci_cp) == 65001 // UTF-8
  set local str_len ~ strlenutf8 $(str)
else
  set local str_len ~ strlen $(str)
endif
```
with just
```
set local str_len ~ strlensci $(str)
```
