### ISSUE TITLE
INPUTBOX close effect

### ISSUE THREAD

**Issue by mjkrg** [d0vgan/nppexec#41]
I was expecting that when the INPUTBOX dialog was closed, the `$(INPUT)` variable would be an empty string but it rather contains the previously OK'd string. If this behavior is preferred, then there should be a way to detect whether the user action was OK or CANCEL in order for the executing script to know how to proceed.

**Comment by d0vgan** [comment]
Fixed in 'develop':
https://github.com/d0vgan/nppexec/commit/542e786d9440b7992d257942471a565d5eaa98ae
Will be included in the next release of NppExec.

**Comment by mjkrg** [comment]
Cool. While we're at it, could we have the Escape key close the dialog box as is standard rather than using the mouse?

----- Original Message -----
Date: Mon, Jun 14, 2021 at 7:29 AM

**Comment by d0vgan** [comment]
Just wondering: what is the purpose of calling `inputbox` without providing any input value?

**Comment by mjkrg** [comment]
Mostly human error. Imagine a case where you have an NppExec script that does something with your input (e.g. uses it as email subject/recipient, commit message, Twitter post, etc.) However, after triggering it, you realize you need to make some changes before proceeding with the action, which means you want the process stopped. That's where you may want to close the dialog without providing a value. Currently, submitting a blank input works like the commit you just pushed but I often found myself closing the dialog box rather than submitting an empty input.

----- Original Message -----
Date: Mon, Jun 14, 2021 at 10:19 AM

**Comment by d0vgan** [comment]
https://github.com/d0vgan/nppexec/commit/91d317f41067f55db0c5a2c29dbf8123f1f083f7

**Comment by mjkrg** [comment]
Nice. Thanks bud.

----- Original Message -----
Date: Mon, Jun 14, 2021 at 3:59 PM

**Comment by d0vgan** [comment]
https://community.notepad-plus-plus.org/topic/21365/nppexec-latest-development-version

**Comment by d0vgan** [comment]
https://github.com/d0vgan/nppexec/releases/tag/v07
