### ISSUE TITLE
assigned keycodes for user scripts shifts up by one 

### ISSUE THREAD

**Issue by artie-finkelstein** [d0vgan/nppexec#42]
NppExec 0.62 test release (2021.06.20 13:59) (I reference this as 0.62.1 in my testing)

Notepad++ v8.1   (32-bit)
Build time : Jun 17 2021 - 01:52:11
Path : C:\Programs\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : NppExec.dll 

All my configured keycodes for NppExec scripts (as shown in the bottom of the NppExec plugin menu) end up shifted up by one position.  Please see the two attached captures: "NppExec 0.62 plugin menu.jpg" is the correct and working version using the dll released on 2021.02.25 11:44 while "NppExec 0.62.1 plugin menu.jpg" shows the resulting 'shift up by one' using the release dated 2021.06.20 13:59.  The scripts still work if invoked from the console or the now incorrectly mapped keycodes.

![NppExec 0 62 plugin menu](https://user-images.githubusercontent.com/28426654/122704049-75a92700-d218-11eb-9177-baecb1abd03c.jpg)
![NppExec 0 62 1 plugin menu](https://user-images.githubusercontent.com/28426654/122704053-7b9f0800-d218-11eb-8572-482c98a6cb81.jpg)

**Comment by d0vgan** [comment]
This is not directly related to NppExec, it is rather how Notepad++'s Shorcut Mapper works.
When you open the file "shortcuts.xml", you may see entries similar to the following:

```
<PluginCommand moduleName="NppExec.dll" internalID="19" Ctrl="yes" Alt="yes" Shift="no" Key="112" />
```

What it demonstrates is the fact that the Shorcut Mapper assigns shortcut keys using the _menu item IDs_.
The latest development version of NppExec has a new menu item "Change Execute Script Font...", so all the menu IDs after it were increased by 1.
So you may open the file "shortcuts.xml" and manually increase the value of `internalID` for each NppExec's item to fix this.

**Comment by artie-finkelstein** [comment]
Thank you for the fast and lucid response.  I'd never deeply thought
about how shortcuts were mapped, and other than remembering to only
edit the .xml file with Microsoft Notepad never gave it much thought.

I suggest you add some sort of warning about this for people updating
from previous versions of NppExec, as I doubt I am the only person
that doesn't know that a new feature in a plugin implies the
shortcuts.xml may need correcting.

Again, thanks for the quick response.
