### ISSUE TITLE
[Feature request] Make the "======= READY =======" message editable

### ISSUE THREAD

**Issue by ThePirate42** [d0vgan/nppexec#43]
When I found ot that NppExec had added the feature to deactivate the `======= READY =======` message I was happy, I always tought that that message is a bit cumbersome. But, after deactivating it, I found out that, without a clear indication of when a process/command ends, the experience can become a lot more confusing. Wouldn't it be better if `======= READY =======` was just a default and everyone could set their own personalized "READY" messages? Like the editable prompts that a lot of modern shells feature. Bonus points if there isn't necessarily a forced newline at the end, or, even better, if variable sostitution is supported.

**Comment by d0vgan** [comment]
I'll consider this. Not sure how to include/exclude a new line at the end, though. Are you proposing to use e.g. \r and \n for that?

**Comment by d0vgan** [comment]
https://github.com/d0vgan/nppexec/releases/tag/v07

**Comment by ThePirate42** [comment]
Thank you!
