### ISSUE TITLE
$(#N) doesn't always evaluate correctly in NppExec 0.62 DLL dated 2021.06.21

### ISSUE THREAD

**Issue by artie-finkelstein** [d0vgan/nppexec#44]
with 'START' as a local index variable across the number of files open:
echo $(#$(START)) <-- #$(START)   evaluates correctly
echo #$(START)   = $(#$(START))    displays ) instead of the file path of the indexed buffer

this code:
```
echo START=$(START)
set local foo = $(#$(START))
echo foo  = $(foo)
echo #$(START)   = $(#$(START))
echo string $(#$(START))
echo #$(START)   = $(foo)
echo $(#$(START)) <-- #$(START)
echo
echo $(#$(START))echo START=$(START)
set local foo = $(#$(START))
echo foo  = $(foo)
echo #$(START)   = $(#$(START))
echo string $(#$(START))
echo #$(START)   = $(foo)
echo $(#$(START)) <-- #$(START)
echo
echo $(#$(START))
```
generates:
```
START=4
foo  = C:\Users\mas\Documents\Lime Kiln Creek\Home Theater\media tweaks needed (2021.07.04).txt
#4   = )
string C:\Users\mas\Documents\Lime Kiln Creek\Home Theater\media tweaks needed (2021.07.04).txt
#4   = C:\Users\mas\Documents\Lime Kiln Creek\Home Theater\media tweaks needed (2021.07.04).txt
C:\Users\mas\Documents\Lime Kiln Creek\Home Theater\media tweaks needed (2021.07.04).txt <-- #4

C:\Users\mas\Documents\Lime Kiln Creek\Home Theater\media tweaks needed (2021.07.04).txt
```
most of the above cases were created to try to narrow down the misbehavior; only the second case evaluates incorrectly

current debug info:
```
Notepad++ v8.1.1   (32-bit)
Build time : Jul  1 2021 - 14:04:28
Path : C:\Programs\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : NppExec.dll 
```
full script file:
[nppBuffer.zip](https://github.com/d0vgan/nppexec/files/6780046/nppBuffer.zip)

**Comment by d0vgan** [comment]
Should be fixed in https://github.com/d0vgan/nppexec/commit/f675e55113acd0d987659a8a2aad4783ffaa5d9a

**Comment by artie-finkelstein** [comment]
Thank you for the heads up.  I'll gladly test it after the next 32 bit
DLL is released.

**Comment by d0vgan** [comment]
https://community.notepad-plus-plus.org/topic/21365/nppexec-latest-development-version/5

**Comment by artie-finkelstein** [comment]
Sorry for the slow reply.  There was a local lightning strike that
took out my phone & internet service for the day.

The NppExec 0.699 works very nicely.  The direct and indirect
referencing to $(#) works as desired now.

I do have a question-  What do the various new 'local' attribute
additions let me accomplish that I couldn't without them?  Is it
really just allowing me to not have to clean up after myself in the
closing lines of a script?  Of course, now that I write that, it
occurs to me that I would no longer have to maintain a common 'known
good state' and always return to it at the end of each script.  Am I
underselling or undervaluing these new attributes and therefore
missing a bigger picture?

Thank you for the fix to $(#).

**Comment by d0vgan** [comment]
The idea of the "local" keyword has two main effects in mind:
1) ability to automatically return to the previous state, whatever it was;
2) no need of manual clean-up.
As an example, let's consider a command "npe_console -- m- v+". It disables the Console's "internal" messages (in green) and enables the $(OUTPUT) variable. To do the opposite, you may execute another command "npe_console -- m+ v-" later. The question is : what was the original state of "m" and "v" before the first command "npe_console -- m- v+" has been executed? Maybe the "internal" messages were already disabled and/or the $(OUTPUT) variable was already enabled before executing "npe_console -- m- v+" ? In such case, executing "npe_console -- m+ v-" later, we will actually change the state of "m" and "v" comparing to how it was before the first command. And here is when "npe_console local -- m- v+" comes in handy: it guarantees that the state of "m" and "v" will be reverted exactly to their previous values.

**Comment by artie-finkelstein** [comment]
Thank you for that very clear explanation.

And THANK YOU for creating the most useful Npp plugin.

**Comment by artie-finkelstein** [comment]
Oops.  I forgot to come here to close the issue earlier.  Mea culpea.
