### ISSUE TITLE
Processing of IF statements fails under certain circumstances

### ISSUE THREAD

**Issue by dinkumoil** [d0vgan/nppexec#45]
## Description

Processing of `IF` statements fail with an error message, when the left hand value of the comparison operator is a string that contains the `"` sign.

## Steps to Reproduce

In one of my scripts there is the line

```
if "$(CLIPBOARD_TEXT)" != "" goto :SHOW_RESULT
```

If the clipboard contains text which contains a `"` sign (for example `This is a "testing" text`), I get an error message:

```
; executing: IF "This is a "testing" text
" != "" goto :SHOW_RESULT
- Syntax error in the if-condition.
To prevent unpredictable behavior, the script is stopped.
```

If I change the line to

```
if "" != "$(CLIPBOARD_TEXT)" goto :SHOW_RESULT
```

the statement is processed without an error.

## Additional Info

Previous versions of `NppExec` were able to process this line without any error. Could be related to

```
changed: now NppExec supports quoted strings in the form of "abc", 'abc' and `abc`.
```

## Applies to

`NppExec` v0.7
Notepad++ v8.1.2

**Comment by d0vgan** [comment]
In fact, the previous version of NppExec has other problems parsing the `IF` arguments, so that part of code was rewritten to be more strict in terms of syntax. So now extra `"` within another pair of `""` leads to syntax error.
This will work with embedded `"`:
```
if `$(CLIPBOARD_TEXT)` != `` goto :SHOW_RESULT
```
This will work with any text:
```
set local len ~ strlen $(CLIPBOARD_TEXT)
if $(len) != 0 goto :SHOW_RESULT
```

**Comment by dinkumoil** [comment]
Why does

`if "" != "$(CLIPBOARD_TEXT)" goto :SHOW_RESULT`

not fail? Is this guaranteed to be save or might this fail too?

**Comment by d0vgan** [comment]
Your last condition does not fail because the function `IsConditionTrue` is written is such way :) You may take a look:
https://github.com/d0vgan/nppexec/blob/f23b9980d7cab4ef8fbc41c1c4dc76a353195b48/NppExec/src/NppExecEngine.cpp#L3698
First it finds the first operand (named `op1` in the code), then it finds the condition (`cond`), finally it finds the second operand (`op2`).
Due to this implementation, `op1` should satisfy the syntax rules whereas `op2` may not. This may or may not be changed in the future.

**Comment by dinkumoil** [comment]
Thanks for clarification.

**Comment by d0vgan** [comment]
I think I'll also experiment with delayed $(var) substitution under the `IF` statement. In case of delayed substitution, first it will parse the initial statement as is - e.g. `if "$(var)" == ""` will give `op1`=`"$(var)"` and `op2`=`""`, and only after that the actual value of $(var) will be substituted into `op1`.

**Comment by d0vgan** [comment]
Please try NppExec20210729_dll from https://sourceforge.net/projects/npp-plugins/files/NppExec/NppExec%20Plugin%20%28dev%29/
It should work in all the cases (because it uses the delayed $(var) substitution).

**Comment by dinkumoil** [comment]
Thanks! Tested and works.
