### ISSUE TITLE
Extra internalID being reserved without a function?

### ISSUE THREAD

**Issue by Gitoffthelawn** [d0vgan/nppexec#46]
Thank you for the v0.7 release.  Overall, it looks great.

I noticed that my keyboard shortcut for a NppExec macro no longer worked.

To get it to work, in Notepad++'s `shortcuts.xml`, I had to change:
```
<PluginCommand moduleName="NppExec.dll" internalID="22" Ctrl="yes" Alt="no" Shift="yes" Key="50" />
```
to:
```
<PluginCommand moduleName="NppExec.dll" internalID="23" Ctrl="yes" Alt="no" Shift="yes" Key="50" />
```

Simple enough.  But note that in Notepad++'s `Shortcut Mapper` UI, there is now a blank line for NppExec after `Help/About`.  Is this a little bug, or is it intentional?  It's like NppExec is reserving an extra `internalID` that it is not using.

**Comment by d0vgan** [comment]
Please find it explained here:
https://github.com/d0vgan/nppexec/issues/42

**Comment by Gitoffthelawn** [comment]
Thanks so much.  Your explanation in #42 makes perfect sense.  The only curiosity is the blank item in Notepad++'s `Shortcut Mapper` for NppExec.  Do you happen to know what is causing that?

**Comment by d0vgan** [comment]
I hardly recalled that the blank item in Notepad++'s Shortcut Mapper for NppExec has a special purpose.
NppExec's Advanced Options has a check-box "Place to the Macros submenu". When it is checked, the NppExec's script menu items are moved from NppExec submenu to Notepad++'s Macro submenu. These script menu items include at least one menu item separator - right before the first script menu item. There can be more menu item separators added via NppExec's Advanced Options. And to be able to move them (these menu item separators) from NppExec submenu to Notepad++'s Macro submenu, they need to have menu item id that, in its turn, leads to an empty item in Notepad++'s Shortcut Mapper for NppExec.
![NppExec_script_menu_items_under_Macro](https://user-images.githubusercontent.com/2848457/127528115-523932c3-052d-4960-95e5-1326983af1c3.png)
![NppExec_Shortcut_mapper](https://user-images.githubusercontent.com/2848457/127528873-d6c6bd60-5c40-42f2-9b6b-6ac6bc7f8efd.png)

**Comment by Gitoffthelawn** [comment]
Ah! You figured it out. Great job.

Would it make sense to add something like "Separator" or "Separator (do not use)" as a name string for those items?  No big deal either way now that I understand what's going on, but other people might appreciate it (and I might forget!).
