### ISSUE TITLE
[Feature] Dynamic reloading of the NPEs script file while Notepad++ is running

### ISSUE THREAD

**Issue by pidgeon777** [d0vgan/nppexec#52]
I was wondering if there is a way to externally modify and reload the `npes_saved.txt` script file, while Notepad++ is active.

Or it is needed to close and reopen Notepad++ every time to load the externally applied modifications to the script file?

**Comment by d0vgan** [comment]
Please try NppExec20220401 instead. The previous implementation had a couple of bad decisions.

**Comment by d0vgan** [comment]
https://github.com/d0vgan/nppexec/releases/tag/v081
