### ISSUE TITLE
NppExecScript echo newline, npe_cmdalias, con_colour, and con_filter

### ISSUE THREAD

**Issue by David-Maisonave** [d0vgan/nppexec#54]
### 1. In my NppExec script, I'm trying to do a single echo with new line, but I can't seem to get it to work. 
The reason I need to use a single echo, is because I'm setting a npe_cmdalias key, in which I want it to list the available commands for the script.
    Here's an example:
``npe_cmdalias ? =echo Console-shortcuts\nR=Run Script\ns=shows all local variables\nh=show NppExec console commands\n!=Show all console commands in detail``
In a normal DOS console the following two methods works for producing new lines in a single echo:
````
echo Method 1
echo R=Run cmd /c ("E:\_Dev\Scripts\NppTest\_WorkingScripts_\ValidScripts\HelloWorld.cmd")&echo\ run=Run cmd /c ("E:\_Dev\Scripts\NppTest\_WorkingScripts_\ValidScripts\HelloWorld.cmd")&echo\ h=show NppExec console commands&echo\ !=Show all console commands in detail

echo Method 2
setlocal EnableDelayedExpansion
(
set \n=^
%=Don't remove this line=%
)
echo R=Run cmd /c ("E:\_Dev\Scripts\NppTest\_WorkingScripts_\ValidScripts\HelloWorld.cmd");!\n! run=Run cmd /c ("E:\_Dev\Scripts\NppTest\_WorkingScripts_\ValidScripts\HelloWorld.cmd");!\n! h=show NppExec console commands;!\n! !=Show all console commands in detail
````
I can't get any of these methods to work in the script.
- [ ] **Is there a way to include new line character in an echo for the NppExec console?**

### 2. I created an alias for help and **help all**
````
  npe_cmdalias h =help
  npe_cmdalias ! =help all
````
The h command works with no problem, but when I try using !, I get the following error:
``This command is not supported by the help utility.  Try "all /?".``
- [ ] **Is there a way to get [help all] to work with alias key?**

### 3. Setting color to blue, before issuing the Execute command.
I put this at the top of the script:``con_colour fg = 0000FF``
Right before I issue the Execute command, i reset the color ``con_colour fg = 0``
I expected that all the output before the execute command would be in blue text, but instead it's being display in green.
- [ ] **Does this setting only effect the output from the execute command?**
- [ ] **If so, is there a way to change the green color from the script?**

### 4. con_filter not working.
I prefixed the output shortcut key with "Console-shortcuts", and created a highlight for it, but it's not working.
````
set Highlight10 = Console-shortcuts*
set Include5 = *
con_filter +i5 +h10
````
But the line never gets highlighted.  I even tried sending a line in a batch file with the keyword, but it still failed to highlight.

- [ ] **Am I doing something wrong?**
- [ ] **How do I set the color to a specific highlight number?**

````

**Comment by David-Maisonave** [comment]
Another question.
For NppExec scripts, is there a way to use "**or**" in an if statement? ``if $(ext) == .bat or $(ext) == .cmd``

**Comment by d0vgan** [comment]
By the way, I believe the existing command `con_colour` can be enhanced to set the message and error colour, e.g.
`con_colour msg = ...`
`con_colour err = ...`
as well as
`con_colour local err = ... msg = ...`
so separate commands `con_colour_msg` and `con_colour_err` will not be needed for this.
Also, `con_colour` already supports `con_colour local bg = ...` that seems to do what `con_colour_bkgrnd` is intended to do.

**Comment by David-Maisonave** [comment]
Compilers having **line** before the number, did not have a colon, or anything between the word "line" and the number.
Here's how Python reports the error:
````
  File "E:\_Dev\Scripts\NppTest\_WorkingScripts_\BadHelloWorld\BadHelloWorld.py", line 8, in <module>
  File "E:\_Dev\Scripts\NppTest\_WorkingScripts_\BadHelloWorld\BadHelloWorld.py", line 5, in main
````

You can test that via following:
````
cmd /c echo File "E:\myproject\aaa.txt", line 5
cmd /c echo File E:\myproject\aaa.txt line 5
````

FYI:
I tested 26 programming languages, and a few don't display the error file name and line number.
The regex code works on all 21 which produced file names and line numbers.

My goal is to have the NppExec script work on at least 50 programming languages, and for the regex code to support any of the 50 which produce errors with file names.


**I just realized there's a bug in the code!**  It's supposed to pickup the line position.
````
cmd /c echo File E:\myproject\aaa.txt:5:9:
cmd /c echo File E:\myproject\aaa.txt:5 char:41
````
That was working before.  I'm checking now to see what happen to break it.

**Comment by d0vgan** [comment]
Regarding multiple lines pasted to NppExec's Console, it is a known limitation that only the last line is processed.
I was thinking about supporting of multi-line pasting and even created a roadmap for that. Currently this roadmap is not available because my PC can't start (so I'm using a laptop), but, in short, there are two directions to be implemented:
- multi-line pasting when a console process is running: these lines go to the process'es input;
- multi-line pasting while no console process is running: these lines go to a new NppExec script. This latter case requires more deep changes, but for the moment I can't recall what are the exact challenges there.

**Comment by David-Maisonave** [comment]
Thanks for your help.
I'm closing this, and I'll follow-up when needed on a new item.
