### ISSUE TITLE
scroll bars not colored based on N++ theme

### ISSUE THREAD

**Issue by MarcinT93** [d0vgan/nppexec#58]
There is a really small issue but for esthete like me its quite irritating - scroll bars for console are not colored based on N++ theme but instead use standard Windows colors.

**Comment by d0vgan** [comment]
Are scroll bars colored in Notepad++'es editing window?

**Comment by dev-muppet** [comment]
Yes, if you use Dark Mode with Notepad++ the scrollbars are dark for Notepad++ but light for NppExec.

![image](https://user-images.githubusercontent.com/105130030/167271489-44e222e4-7c6b-4cf4-8618-b70c1383b0b7.png)

**Comment by d0vgan** [comment]
Thanks, I'll see what I can do.

**Comment by d0vgan** [comment]
Looks good in Notepad++ 8.4.4. 
![NppExecConsoleDarkMode](https://user-images.githubusercontent.com/2848457/179517025-e00cb559-815c-4b92-a24e-b2253731c7b4.png)
