### ISSUE TITLE
Feature request: separate Kill and Send with predefined commands.

### ISSUE THREAD

**Issue by mrrezaie** [d0vgan/nppexec#59]
Dear Developers,

Merry Christmas and happy holidays.

First of all, thank you so much for developing this plugin. It is very useful and practical.

When I execute my script (Python), a window is opened and asks me whether to kill the terminal or send a command to it. It would be great if you separate these two. I usually select several lines of my script and send it to the active terminal. It always needs two action (executing and sending). I set a shortcut for executing (Ctrl+Enter) and a command ($(CURRENT_WORD)) to send the selected lines. Every time I must press Ctrl+Enter and again Enter. Imagine a button (or command with shortcut) for just killing the terminal, and one for sending to the terminal, both with predefined values or commands. With this, no more than one action is needed anymore (the same as vscode) and it makes the plugin more user-friendly.

I look forward to seeing your new features.

Best regards,
Mohammadreza

**Comment by d0vgan** [comment]
The NppExec Manual, section "4.6.4. Running Python & wxPython" mentions the `@exit_cmd_silent` variable that allows to exit a running instance of Python automatically. Is it what you are looking for?
```
set local @exit_cmd_silent = exit()  // allows to exit Python automatically
```

**Comment by mrrezaie** [comment]
Hi,

Thanks for your reply. 
Not exactly. I'm looking for a convenient way to send the selected lines of code into console, with only one click (or keyboard shortcuts) . As I mentioned previously, the current method needs two actions.

Best,
MrR

**Comment by d0vgan** [comment]
Do I understand correctly that you want to select a few lines in the editor (in Notepad++'es editing window) and send these selected lines to the _already running instance_ of Python (i.e. to Python that is already running in NppExec's Console)?
If so, currently NppExec does not support this.
However, here is what is possible: you are able to _restart_ Python (i.e. to exit the running instance of Python by means of the `@exit_cmd_silent`) and send multiple commands to the new instance of Python using the technique described in NppExec Manual, section "4.6.9. Send several commands to external tool". E.g.:
```
set local @exit_cmd_silent = exit()  // allows to exit Python automatically
sel_saveto $(SYS.TEMP)\npp_sel.py :a // saving the selected text into npp_sel.py in ANSI encoding
python -i -u "$(SYS.TEMP)\npp_sel.py"  // run Python's program interactively
```

**Comment by mrrezaie** [comment]
> Do I understand correctly that you want to select a few lines in the editor (in Notepad++'es editing window) and send these selected lines to the already running instance of Python (i.e. to Python that is already running in NppExec's Console)?

Exactly, something like `SendCode` and `Terminus` plugins do in Sublime text.

**Comment by d0vgan** [comment]
I agree this adds another dimension to NppExec. I'm experimenting with two new menu items: Execute Selected Text and Execute Clipboard Text. Such changes do not come alone: when we have such menu items, it looks logical to add a new command NPP_EXECTEXT that may take e.g. $(CLIPBOARD_TEXT) or $(SELECTED_TEXT) as a parameter. Such changes require some additional internal updates. For example, I'm experimenting with ability to execute so-called collateral (parallel) scripts by means of Execute Selected Text, Execute Clipboard Text and NPP_EXECTEXT.
We shouldn't forget that all these changes take time. New features do not come from nowhere, they require hours to be spend on development and testing.

**Comment by d0vgan** [comment]
Please try the latest binaries from https://sourceforge.net/projects/npp-plugins/files/NppExec/NppExec%20Plugin%20%28dev%29/

**Comment by mrrezaie** [comment]
Dear Dovgan,

It is working well as requested. Thank you so much for your endeavors.

All the Best,
MrR
