### ISSUE TITLE
Can't launch PyQt5 via nppexec

### ISSUE THREAD

**Issue by simonchih** [d0vgan/nppexec#6]
The .py file is using PyQt5, code below:
```
#!/usr/bin/python3
# -*- coding: utf-8 -*-

"""
ZetCode PyQt5 tutorial 

In this example, we create a simple
window in PyQt5.

Author: Jan Bodnar
Website: zetcode.com 
Last edited: August 2017
"""

import sys
from PyQt5.QtWidgets import QApplication, QWidget

if __name__ == '__main__':
    
    app = QApplication(sys.argv)

    w = QWidget()
    w.resize(250, 150)
    w.move(300, 300)
    w.setWindowTitle('Simple')
    w.show()
    
    sys.exit(app.exec_())
```

Nppexec commands below:
```
NPP_SAVE
CD $(CURRENT_DIRECTORY)
SET python = D:\Program Files (x86)\Python36-32\python.exe
"$(python)" -u "$(FULL_CURRENT_PATH)"
UNSET python
```

The console shows program is start,
but PyQt5 GUI is NOT launched

**Comment by d0vgan** [comment]
Maybe the solution here is similar to "Running Python scripts using wxPython" part of the section "4.6.4. Running Python & wxPython" of the NppExec Manual?

**Comment by simonchih** [comment]
By the NppExec help manual, we can set "app = App(redirect=False)"  for wxPython, but I don't know how to set redirect=False in PyQt5...

**Comment by d0vgan** [comment]
Unfortunately, I can't provide expertise on PyQt5. I was going to try it, but according to this page it's not easy even to install it:
https://stackoverflow.com/questions/25589103/how-to-install-pyqt5-on-windows-for-python-2
I think you better be asking Python/PyQt5 folks, they surely have more knowledge in this area. The only thing related to NppExec here is the fact that NppExec does not provide a real console window and uses pipes to redirect the console input and output. This is the general description of the problem, and I believe the Python/PyQt5 folks are already aware of how to deal with it.
It could be great if you could share the answer here once it is provided by Python/PyQt5 experts.

**Comment by simonchih** [comment]
Thanks your survey for PyQt5. I am NOT PyQt5 expert too. But there is easy workaround for Npp (NOT for Nppexec). That is Npp -> Run command. e.g. 
C:\Program Files (x86)\Python37-32\Lib\idlelib\idle.bat “$(FULL_CURRENT_PATH)”
