### ISSUE TITLE
Possible regression 20220128 dev build

### ISSUE THREAD

**Issue by vinsworldcom** [d0vgan/nppexec#61]
See [here](https://community.notepad-plus-plus.org/topic/21365/nppexec-latest-development-version/24?_=1643644416604):

I have a global set:

```
SET CMD=cmd.exe /d /c
```

And I use it in scripts - for example:

```
$(CMD) start $(NPP_DIRECTORY)\change.log
```

and this launches Notepad.exe (my default .log editor apparently) with change.log.

In the new version, running that second script - nothing happens. It seems the $(CMD) variable isn’t launching external processes anymore? Other things like:

```
$(CMD) dir /b /ad $(NPP_DIRECTORY)
```

do work.  The previous 0.7.1 version of NppExec did fine launching the external processes.

Cheers.

**Comment by vinsworldcom** [comment]
Maybe a settings checkbox to enable/disable one or the other.  For me
personally, if NPPexec launches an external process and I want to kill it,
I go to that external process and kill it rather than expecting a control-c
in the NPPexec console to do that for me.

Cheers.

**Comment by d0vgan** [comment]
Well, I think the old behavior needs to be preserved by default - to be consistent with the standard command prompt.
And the new one, where the process tree is killed, will be enabled e.g. by `npe_console j+`.

**Comment by vinsworldcom** [comment]
Happy to test when available.

**Comment by badrelmers** [comment]
This bug have nothing to do with ctrl-c behavior described here https://github.com/d0vgan/nppexec/issues/60
it happens in the default dll of 20220128 dev build
and it is caused by the new feature of killing the childs
in fact notepad open then close quickly like that:
you run
```bash
$(CMD) start $(NPP_DIRECTORY)\change.log
```
then `cmd` exit, then Nppexec will kill notepad thanks to the new feature (killing the childs)

so this is a feature not a bug I think.

it can be solved easily by adding `/wait` flag so `cmd` do no exit:
```bash
$(CMD) start /wait $(NPP_DIRECTORY)\change.log
```

**Comment by badrelmers** [comment]
or it can be solved by using npp_run:
```bash
npp_run $(CMD) start $(NPP_DIRECTORY)\change.log
```
or simply
```bash
npp_run $(NPP_DIRECTORY)\change.log
```

**Comment by vinsworldcom** [comment]
Indeed, the /wait to the `start` command seems to fix it.  Thanks!

**Comment by badrelmers** [comment]
> Well, I think the old behavior needs to be preserved by default - to be consistent with the standard command prompt.
> And the new one, where the process tree is killed, will be enabled e.g. by npe_console j+

you are right, new comers will think that NppExec do not work, the feature of killing childs should be enabled when needed not by default to be consistent with the standard command prompt as you said.

**Comment by badrelmers** [comment]
@vinsworldcom
your case can be solved by using `npp_run  $(POWERSHELL)...` instead of `$(CMD) start $(POWERSHELL)...`

`npp_run` is not affected  by the new feature (killing childs)

**Comment by vinsworldcom** [comment]
YES - you're right, just tested.

Thank you @badrelmers  and @d0vgan for the help.  I ***LOVE*** this plugin - evidence my 2850+ line `npes_saved.txt`!

**Comment by vinsworldcom** [comment]
@badrelmers , @d0vgan took some time yesterday to go through my large `npes_saved.txt` and it seems there are many places where I can replace `cmd.exe /d /c => $(CMD)` for `NPP_RUN ...` and things work as expected.  I use the `$(CMD)` to run "Batch" commands like `if exist ...`, `for /f %i in ...` but was also using it to "launch" applications like `$(CMD) explorer.exe ...` which it seems are better suited to `NPP_RUN ...`.

Thanks for your patience and help - I use this plugin everyday I'm in Notepad++ to automate so many tasks yet I still seem to have only scratched the surface of understanding what's possible or the best way to implement things.

Cheers.

**Comment by badrelmers** [comment]
yes d0vgan really made a good work, he made the beautiful Notepad++ to become something more beautiful. thanks to him and his time and nice work

**Comment by d0vgan** [comment]
Please try the latest version NppExec20220203_dll here:
https://sourceforge.net/projects/npp-plugins/files/NppExec/NppExec%20Plugin%20(dev)/

**Comment by badrelmers** [comment]
`NPE_CONSOLE j+/j-`  works perfectly
this is great, thank you so much d0vgan
