### ISSUE TITLE
Notepad 8.2.2 development fixes

### ISSUE THREAD

**Issue by vinsworldcom** [d0vgan/nppexec#62]
See here:

https://community.notepad-plus-plus.org/topic/22471/recompile-your-x64-plugins-with-new-header

So long as it seems you're in an update cycle, grab the latest from Notepad++ repo:

+ notepad-plus-plus/scintilla/include/Scintilla.h
+ notepad-plus-plus/scintilla/include/Sci_Position.h

before compiling your final release.  I haven't seen NppExec crash the dev build of Notepad++ for me in my testing.  Not sure if you're using [SCI_GETTEXTRANGE](https://www.scintilla.org/ScintillaDoc.html#SCI_GETTEXTRANGE) or [SCI_GETSTYLEDTEXT](https://www.scintilla.org/ScintillaDoc.html#SCI_GETSTYLEDTEXT) anywhere in your code, but those ***seem*** to be the only calls affected by the header change that result in a crash.

The other thing to consider is if someone tries:

```
SCI_SENDMSG SCI_GETTEXTRANGE ...
```

from the NppExec console - though I'm not sure how they'd create the `LPARAM` pointer required to return the structure that call generates.

Cheers.

**Comment by d0vgan** [comment]
So I was right!!! :)
https://github.com/d0vgan/nppexec/blob/master/NppExec/src/NppExecEngine.cpp#L7024

**Comment by d0vgan** [comment]
Please try the latest version NppExec20220203_dll here:
https://sourceforge.net/projects/npp-plugins/files/NppExec/NppExec%20Plugin%20(dev)/

**Comment by d0vgan** [comment]
NppExec v0.8.
