### ISSUE TITLE
Built in "NPE_CONSOLE local -- x+" hard codes 0xa01010 red color

### ISSUE THREAD

**Issue by dev-muppet** [d0vgan/nppexec#66]
The new (and excellent) "NPE_CONSOLE local -- x+" feature always uses the hardcoded default color:

const COLORREF COLOR_CON_TEXTERR  = RGB(0xA0, 0x10, 0x10);

If a custom TextColorError is set in "Advanced Options" I observe that this color is used only for NppExec messages and is not used to highlight compiler messages. There is at present no way to customize the color for "NPE_CONSOLE local -- x+".

**Comment by d0vgan** [comment]
Indeed. To fix it, find this line in "WarningAnalyzer.cpp":
```
pszMask = m_BuiltInErrorFilter.Mask;
```
and add the following line right after it:
```
m_BuiltInErrorFilter.Effect.rgb = Runtime::GetNppExec().GetConsole().GetCurrentColorTextErr();
```

**Comment by d0vgan** [comment]
https://github.com/d0vgan/nppexec/commit/ef1aee98ab98ed630ea22413afa8e91431e5af87
I've also fixed the hack with indexing at the "-1"th element. It took me time to recall how and why it worked before :)
