### ISSUE TITLE
Ipython does not have auto-indentation and colour for keywords. The same things work fine in normal command prompt. 

### ISSUE THREAD

**Issue by debajyoti1990** [d0vgan/nppexec#75]

**Comment by d0vgan** [comment]
I assume Ipython is the one that can be installed by the following instructions:
https://ipython.org/install.html

Unfortunately, NppExec Console does not support colors of the child processes. The NppExec Manual tries to explain this in the section 1.3:
```
- NppExec is not a console emulator. NppExec redirects the running process'es output to its
Console window, and can redirect the Console window's input to the running process (with some
limitations).
The NppExec's Console is not a "real" console window (actually, it uses RichEdit control for text
input/output), it does not provide a console screen buffer. Thus, a console application which
requires a "real" console screen buffer must be run in its own console window (using NPP_RUN
command).
```

I don't know why ipython's auto-indentation does not work.
What can be done, however, is to write your python code directly in Notepad++'s editing window and then use NppExec's Execute Selected Text to send the selected text to ipython. You may assign a shortcut key to the Execute Selected Text command to invoke it using the keyboard.

**Comment by debajyoti1990** [comment]
Thanks for explaining @d0vgan , the plugin, although not console emulator, is still excellent 😀. The colour of ipython is a minor thing really, but please see if you could debug 2hy the auto-indentation is not working. Thanks again for your work !

**Comment by d0vgan** [comment]
Well, exactly 8 bytes are read from the pipe (in `CChildProcess::readPipesAndOutput`) after Enter is pressed:
* dwBytesRead = 8
* Buf = 0x070ec8e8 "   ...: "

![image](https://user-images.githubusercontent.com/2848457/217640952-ad2a4150-2938-4496-98d0-257c7bfd0029.png)

So NppExec prints exactly these 8 characters.
It's a mystery why additional spaces appear in a real console window while they do not appear in the pipe.
I was also googling for "ipython unbuffered output" as it might help in such cases (python has it: "python -u"), but it looks like ipython does not support such mode:
[CChildProcess::readPipesAndOutput](https://stackoverflow.com/questions/1578592/ipython-in-unbuffered-mode)
Maybe an additional mediator application that achieves real-time reading from the console would help with this as mentioned here:
https://github.com/d0vgan/nppexec/issues/38#issuecomment-857797248
But, hmm, well, this needs a lot of experiments and tweaks, and if it was easy, I would already be adapted to NppExec...

**Comment by debajyoti1990** [comment]
I did some internet search, and found that Sublime's terminus plugin is based on pywinpty python package which in turn is based on winpty library.Also there are integrable console emulators like cmder, alcaritty etc.
 
Could something be done in the above directions to bring a real console emulator in notepad++ ? 

Pardon me, I didn't want to mention Sublime, but I needed some reference point.

**Comment by debajyoti1990** [comment]
Closing this issue.
