### ISSUE TITLE
encoding characters error

### ISSUE THREAD

**Issue by Qumojo** [d0vgan/nppexec#77]
Hi, first, thanks a lot for your hard work creating this fantastic plugin for np++, I love it.

My issue, is that somewhere somehow, the console corrupts the data... I am not a high tech savy and I'm not too sure how to explain the issue, but I've got a picture of what happens in the normal console under windows cmd and what happens under the nppexec one.
![image](https://github.com/d0vgan/nppexec/assets/54639589/340cfb7b-3a2c-4f05-9723-9a4fa22fb478)

Running the script under np++ give that UnicodeEncodeError, but strangely if run directly in that same console, prints the star just fine. Obviously in cmd there is no star, but it doesn't get an error and that's my main thing, I don't mind it printing it badly in the console, I just want to avoid the error/break of the script. Thanks a lot for looking into this.

**Comment by d0vgan** [comment]
According to "4.6.4. Running Python & wxPython":
https://htmlpreview.github.io/?https://github.com/d0vgan/nppexec/develop/NppExec/doc/NppExec/NppExec_Manual/4.6.4.html
you need `env_set PYTHONIOENCODING=utf-8` to instruct Python to output as utf-8.
In such case, `npe_console -- o2 i2` will also be useful to instruct NppExec that the output/input is utf-8. 
To sum up:
```
env_set local PYTHONIOENCODING=utf-8
npe_console local -- o2 i2
set local @exit_cmd = exit()
python -i -u "$(FILE_NAME)"
```

**Comment by Qumojo** [comment]
Yes, this worked perfectly! Thanks you so much once again!
