### ISSUE TITLE
Search index for online version of NppExec Manual

### ISSUE THREAD

**Issue by d0vgan** [d0vgan/nppexec#80]
NppExec Manual is available online:
https://d0vgan.github.io/nppexec/

The usage of HTML frames makes it look similar to the .chm file (_NppExec_Manual.chm_) where there is a left pane with the table of contents and a right pane with the content.
What is missed, comparing to the .chm file, is the ability to search through the pages. It would be great to have a searching ability for the online version.
The source code of the Manual is here, the main entry is "index.html":
https://github.com/d0vgan/nppexec/tree/develop/docs
If anyone has any hints of how the searching ability can be added/implemented, please let me know.

**Comment by d0vgan** [comment]
Not sure whether it is an issue or not: if I search for e.g. `<command>`, the matching words are not highlighted in the documents, whereas seraching for `command>` gives proper highlighting.

**Comment by d0vgan** [comment]
I'm wondering: is it possible to open a given page of the online Manual having the table of contents (TOC) at the left?
Here is what I mean:
- when I navigate to `https://d0vgan.github.io/nppexec`, the page is opened with the TOC at the left.
- when I navigate to a specific page, such as `https://d0vgan.github.io/nppexec/NppExec_Manual/FAQ.html`, it is shown without the TOC.

So, is it possible to use some special form of, maybe, `https://d0vgan.github.io/nppexec/?q=NppExec_Manual/FAQ.html`, to navigate to a specific page plus have the TOC at the left?

**Comment by rdipardo** [comment]
> Not sure whether it is an issue or not: if I search for e.g. `<command>`, the matching words are not highlighted in the documents, whereas searching for `command>` (without the leading `<`) gives proper highlighting.

Definitely a bug, here:

https://github.com/d0vgan/nppexec/blob/3c71e7d01f7bd1f9df02d2cc3b2021e9a0c14a5b/docs/show_matches.js#L7

The faulty code path goes like this:

~~~js
var value = encodeURI('<command>')
var encodedChars = value.match(/%[0-9a-f]{2,}/ig)
// ['%3Cc', '%3E']

encodedChars.forEach(function(ch) {
  // '%3Cc' -> parseInt('3Cc', 16) -> String.fromCharCode(0x3CC) -> 'ό'
  value = value.replace(ch, String.fromCharCode(parseInt(ch.slice(1), 16)))
})
// 'όommand>'
~~~

[encodeURI] should encode each byte in a fixed `%XX` format; a more accurate pattern would be `/%[0-9A-F]{2}/g`

[encodeURI]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI#description

**Comment by rdipardo** [comment]
> So, is it possible to use some special form of, maybe, `https://d0vgan.github.io/nppexec/?q=NppExec_Manual/FAQ.html`, to navigate to a specific page plus have the TOC at the left?

Not with frame sets, no, but maybe by replacing the document's location with the host, parameterized with the path to the requested document, which would then become `frames['content'].location`. . .?

That would make it more complicated to handle errors, like [the one FireFox has with the `file://` protocol][0]. Currently we request the document when `frames['content'].location` is off limits. But if every request triggers another attempt to replace `frames['content'].location`, the result could be an endless loop.

In any case the hypothetical redirection script has to be embedded in every document, the way the search match highlighter is.


[0]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Property_access_denied

**Comment by d0vgan** [comment]
> [encodeURI](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI#description) should encode each byte in a fixed `%XX` format; a more accurate pattern would be `/%[0-9A-F]{2}/g`

Thank you!
How do you debug the JavaScript code between the pages, by the way?
I've realized that the searching for `<command>` is now OK, however the highlighting of the matches do not work for it. I assume it may be a problem related to `<` vs. `&lt;` but I don't have knowledge of debugging in a browser.

**Comment by rdipardo** [comment]
> I've realized that the searching for `<command>` is now OK, however the highlighting of the matches do not work for it.

Yes, only 'show_matches.js' would fail because it has to decode the query string, sometimes wrongly, as above. Keyboard input is fed verbatim to 'search.js', which does not even look at the actual HTML markup; it searches the `NPPEXEC_HELP_TOPICS` JSON blob, and all the content in there has already been parsed by Python, so every `&lt;` is dumped as `<`, etc.

**Comment by rdipardo** [comment]
> How do you debug the JavaScript code between the pages, by the way?

Just insert [the `debugger;` statement](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/debugger), and the browser turns into an IDE!

Note that the semi-colon is mandatory, unlike every other statement in JavaScript. It's also best to run the website locally (e.g, `python3 -m http.server -d ./docs`, so you avoid stepping into whatever tracking scripts may be running on the GitHub Pages server.

**Comment by d0vgan** [comment]
Thank you for the hint! I should confess I did not know about using Python as an HTTP server via `python3 -m http.server -d ./docs` after all the years of writing Python scripts! Probably because I've never written anything web-specific in Python.
The next thing I've discovered that I don't even need to add `debugger;` explicitly since I just can put a breakpoint directly in the Web Developer Tools (F12) - Debugger, at least in Firefox.
Finally, I noticed there are two instances of the "show_matches.js" script: one under the "docs" and another one under the "docs/NppExec_Manual". Not sure whether the one in the "docs" folder is needed. It's hard to test because of caching in browser.

**Comment by rdipardo** [comment]
> I noticed there are two instances of the "show_matches.js" script: one under the "docs" and another one under the "docs/NppExec_Manual". Not sure whether the one in the "docs" folder is needed.

Well, Python's `include_finder_script` function [needs a source file to copy][0], and it seemed easier to keep a static asset near the source tree root. The doc pages load the most adjacent copy in the subdirectory, which is the only one that would be cached.

![d0vgan github io nppexec](https://github.com/d0vgan/nppexec/assets/59004801/b3dd6b40-6094-4269-84bb-bb50f6737b41)

Chrome browsers are especially greedy about caching, but I guess they have to be for acceptable user experience.

[0]: https://github.com/d0vgan/nppexec/blob/3c71e7d01f7bd1f9df02d2cc3b2021e9a0c14a5b/NppExec_parse_help_topics.py#L70

**Comment by rdipardo** [comment]
Getting back to this:

> So, is it possible to use some special form of, maybe, `https://d0vgan.github.io/nppexec/?q=NppExec_Manual/FAQ.html`, to navigate to a specific page plus have the TOC at the left?

I finally noticed what you mean. The hyperlinks in the TOC panel are a bit annoying after the smooth experience of browsing by the search box. All it would take is an event handler to intercept the click and replace `frames['content'].location` instead of navigating. Basically what [the `clickToView` callback][0] is already doing for `<select>` items.

Then again, overriding a static element's default behaviour is usually considered an anti-pattern, especially if the website becomes less accessible (to Firefox users, for example). 

[0]: https://github.com/d0vgan/nppexec/blob/3c71e7d01f7bd1f9df02d2cc3b2021e9a0c14a5b/docs/search.js#L10

**Comment by d0vgan** [comment]
> Getting back to this:
> 
> > So, is it possible to use some special form of, maybe, `https://d0vgan.github.io/nppexec/?q=NppExec_Manual/FAQ.html`, to navigate to a specific page plus have the TOC at the left?
> 
> I finally noticed what you mean. The hyperlinks in the TOC panel are a bit annoying after the smooth experience of browsing by the search box. All it would take is an event handler to intercept the click and replace `frames['content'].location` instead of navigating. Basically what [the `clickToView` callback](https://github.com/d0vgan/nppexec/blob/3c71e7d01f7bd1f9df02d2cc3b2021e9a0c14a5b/docs/search.js#L10) is already doing for `<select>` items.
> 
> Then again, overriding a static element's default behaviour is usually considered an anti-pattern, especially if the website becomes less accessible (to Firefox users, for example).

I have to say I don't really understand this - probably because I failed to explain my initial idea.
OK, let's take Notepad++'s Preferences dialog as an example. When you start a new instance of Notepad++ and open its Preferences dialog, this dialog is always opened at the General page, right?
Similarly, when you open a new instance of https://d0vgan.github.io/nppexec, it is always opened at the Title Page.
Now, what if I tell you I want to run a new instance of Notepad++ with an additional command-line parameter `/preferences=Editing` that will open the very same Preferences dialog, but its Editing page will be active instead of the General page which is activated by default?
In the very similar way, I'd like to be able to specify a url similar to `https://d0vgan.github.io/nppexec/page=FAQ.html` or maybe  `https://d0vgan.github.io/nppexec/index.html?page=FAQ.html`, I don't know, that will invoke the very same "index.html" with TOC at the left (as usually) and with "FAQ.html" at the right (instead of the default Title Page). 
From my point of view, to achieve that, it should be enough to do just one single change similar to:
```
<FRAMESET cols="30%, 70%">
    <FRAME name="toc" src="./NppExec_Manual/toc.html">
    <FRAME name="content" src="getStartPage()">
  </FRAMESET>
```
where `getStartPage()` is something like
```
function getStartPage()
{
  var s = getUrlParam("page");
  if (s == undefined || s == "")
    return "./NppExec_Manual/0. Title Page.html";
  else
    return "./NppExec_Manual/" + s;
}
```
And again, the HTML/JavaScript reality is most likely more complicated, but this is just an idea of how it might be.

**Comment by rdipardo** [comment]
> ```
> <FRAMESET cols="30%, 70%">
>     <FRAME name="toc" src="./NppExec_Manual/toc.html">
>     <FRAME name="content" src="getStartPage()">
>   </FRAMESET>
> ```

The `src` attribute is exactly what the code `parent.frames['content'].location.replace(targetURI)` is modifying in 'search.js'. Clicking a search box item triggers a callback that directly accesses the content frame. This already seems to work fine, except when Firefox is serving the site from a `file:///` URI.

You just need a script on the homepage to parse the "start page" parameter, which is contained by [the `location.search` property][0], and assign it to the content frame's location. There would however be a visible flicker as the static HTML must be loaded before any scripts (to make sure the DOM is in memory first), and the title page is the static value of the content frame's location, so it will always be shown first.

[0]: https://developer.mozilla.org/en-US/docs/Web/API/Location/search

**Comment by rdipardo** [comment]
Hey, @d0vgan, want to try this? Apply the patch, start a local server, and go to something like `http://localhost?q=4.6.4`. It should work even for `file://` paths.

~~~diff
diff --git a/docs/index-local.html b/docs/index-local.html
index af8e07c..401b33b 100644
--- a/docs/index-local.html
+++ b/docs/index-local.html
@@ -7,6 +7,18 @@
     <link href="https://raw.githubusercontent.com/d0vgan/nppexec/master/NppExec/ConsoleIcon.ico" type="image/x-icon" rel="icon">
     <title>NppExec Manual: Index</title>
     <meta http-equiv="Permissions-Policy" content="interest-cohort=()"> <!--Remove warning in browser: feature not enabled: 'interest-cohort'-->
+    <script type="text/javascript">
+      window.addEventListener('DOMContentLoaded', function() {
+        try {
+          var query    = location.search || '';
+          var param    = 'q=';
+          var value    = query.slice(query.indexOf(param) + param.length);
+          if (value) {
+            parent.frames['content'].location.replace('NppExec_Manual/' + value + '.html');
+          }
+        } catch (e) { console.info(e); }
+      })
+    </script>
   </HEAD>
   <FRAMESET cols="30%, 70%">
     <FRAME name="toc" src="./NppExec_Manual/toc.html">
diff --git a/docs/index.html b/docs/index.html
index a1cc821..a55235f 100644
--- a/docs/index.html
+++ b/docs/index.html
@@ -12,8 +12,8 @@
       var protocol = location.protocol;
       var hostname = location.hostname;
       var pathname = location.pathname;
-      var href     = location.href;
-      var newPath  = 'index-local.html';
+      var href     = location.href.replace(location.search , '');
+      var newPath  = 'index-local.html' + location.search ;
       var redir    = href.replace(/\/index\.(php|x?html?)$/, '/'+newPath);
       if (protocol == 'file:') {
         location.replace(redir);
@@ -21,6 +21,16 @@
         redir = (pathname == '/') ? href + newPath : redir;
         location.replace(redir);
       }
+      window.addEventListener('DOMContentLoaded', function() {
+        try {
+          var query    = location.search || '';
+          var param    = 'q=';
+          var value    = query.slice(query.indexOf(param) + param.length);
+          if (value) {
+            parent.frames['content'].location.replace('NppExec_Manual/' + value + '.html');
+          }
+        } catch (e) { console.info(e); }
+      })
     </script>
   </HEAD>
   <FRAMESET cols="30%, 70%">

~~~

**Comment by d0vgan** [comment]
> Hey, @d0vgan, want to try this?

Oh yes!!!

Just one additional question: is it possible to tune the script to handle "404, File not found" (when something non-existing is specified, e.g. "?q=3.1.1") by redirecting to the "0. Title Page.html" page in case of "404"?
(Unfortunately, I'm that bad with HTML scripting to not figure it out myself).
