### ISSUE TITLE
How to get current dir name only (not full path)

### ISSUE THREAD

**Issue by elenderg** [d0vgan/nppexec#87]
Hello. In NppExec we have:

$(FULL_CURRENT_PATH)  :  E:\my Web\main\welcome.html
$(CURRENT_DIRECTORY)  :  E:\my Web\main
$(FILE_NAME)  :  welcome.html
$(NAME_PART)  :  welcome
$(EXT_PART)  :  .html

but not 

$(DIRECORY): main

neither
$(DRIVE) : c:\

I'm aware of

$(WORKSPACE_ITEM_PATH)  :  full path to the current item in the workspace pane
$(WORKSPACE_ITEM_DIR)  :  directory containing the current item in the workspace pane
$(WORKSPACE_ITEM_NAME)  :  file name of the current item in the workspace pane
$(WORKSPACE_ITEM_ROOT)  :  root path of the current item in the workspace pane

but these only work in workspaces.

Any ideas?

**Comment by d0vgan** [comment]
Similarly to most scripting and programming languages, we need to extract it as a substring that follows the last `\` or `/` in the directory path.
For example:
```
npp_console local -
set local dirname = $(CURRENT_DIRECTORY)
set local c ~ substr -1 1 $(dirname)  // trailing (last) character
if "$(c)" == "\" then
  set local dirname ~ substr 0 -1 $(dirname)  // removing trailing \
else if "$(c)" == "/" then
  set local dirname ~ substr 0 -1 $(dirname)  // removing trailing /
endif
set local n1 ~ strrfind $(dirname) \  // position of last \
set local n2 ~ strrfind $(dirname) /  // position of last /
if $(n1) > $(n2) then
  set local n1 ~ $(n1) + 1
  set local dirname ~ substr $(n1) - $(dirname)
else
  set local n2 ~ $(n2) + 1
  set local dirname ~ substr $(n2) - $(dirname)
endif
npp_console local +
echo $(dirname)
```

**Comment by elenderg** [comment]
Thanks for helping.
