### ISSUE TITLE
XBrackets release accidentally added to this repo?

### ISSUE THREAD

**Issue by Gitoffthelawn** [d0vgan/nppexec#89]
Just FYI, I think an XBrackets release was accidentally added to this repo:

https://github.com/d0vgan/nppexec/releases/tag/v80

**Comment by d0vgan** [comment]
You are right, thank you!
Looks like I had accidently executed the "git tag -a v80 -m XBrackets v.8.0" command from the global commands history while I was in NppExec's directory and was going to add the latest changes to the "docs/index.html" and "docs/index-local.html"

**Comment by Gitoffthelawn** [comment]
You're welcome!  It's almost embarrassing that I notice these things... but I know I am amongst friends who appreciate it... ;)
