### ISSUE TITLE
.bat files can't be invoked without extension

### ISSUE THREAD

**Issue by Vyoam** [d0vgan/nppexec#9]
My version: nppExec 0.6 RC2

I have a bunch of .bat files in my %PATH%, which I would like to invoke from nppExec console.

When I execute them from cmd, of course, I don't need to mention the extension. e.g. myScript.bat can be executed in cmd like...
cmd> myScript

But, in nppExec, I need to mention the extension also...
nppExec> myScript.bat

I assure you that this behaviour can be reproduced easily.

Interestingly, for .exe files in %PATH%, nppExec can execute without needing extension.

So, can you please update the plugin so that .bat scripts can be invoked without mentioning extension? Or can this behaviour not be controlled by nppExec?

**Comment by Vyoam** [comment]
![nppexec](https://user-images.githubusercontent.com/1176140/52080682-66c96780-25be-11e9-9876-e747ab2ffac7.PNG)

**Comment by Vyoam** [comment]
FYI, in the screenshot, jv stands for a custom script I created for Java code execution. Nothing fancy there.

**Comment by d0vgan** [comment]
This is the way how NppExec works by means of the WinAPI function CreateProcess.
Because it is "cmd" who actually executes the .bat and .cmd files, the files with .bat and .cmd extension can be run with either explicitly specifying the extension or, alternatively, with a prefix "cmd /c" without extension.
Anyway, if you know an elegant code example that allows to detect whether the first argument corresponds to a batch file (rather than to an executable file) located either in current directory or in some other directory present in the %PATH%, please share it.

**Comment by Vyoam** [comment]
Got you. Will look into it. I need to explore the code more, but for reference, it seems these links are relevant...
Google "winapi createprocess bat"
https://stackoverflow.com/questions/25919451/use-createprocess-to-run-a-batch-file
https://social.msdn.microsoft.com/Forums/en-US/259d3fe7-1f52-4068-bb12-32788104c798/createprocess-cannot-execute-batch-file?forum=vcgeneral

**Comment by d0vgan** [comment]
Hmm... After I've described everything in all details, looks like the only remaining thing is just to develop it :)

**Comment by Vyoam** [comment]
I think I can try to chip in over the month.

I do not have much knowledge of WinAPI... though, one thing I'd look into would be how cmd or other cmd clones take care of this use case. Then again, it might well be no different than what you discussed.

**Comment by d0vgan** [comment]
Hell, `GetFullPathName` just performs a simple (stupid) concatenation of the current directory and a given file name, without any check whether the full pathname exists or not! This is what happens when you rely on WinAPI without reading every character under the Remarks section :(
Need to find a _working_ way to locate a file by its file name.

**Comment by d0vgan** [comment]
Looking at the sources of sfk (Swiss File Knife), it gets the list of extensions from `%PATHEXT%` and then examines the current directory and then each directory in the `%PATH%` for a presence of the file name with an extension from the `%PATHEXT%`.
I was hoping that WinAPI proposes an existing function to do this, but I couldn't find such a function so far.

**Comment by d0vgan** [comment]
Looks like this does the trick:
https://github.com/d0vgan/nppexec/blob/2703ed2f76e59fd85c34054fbff71c0a2a805ccd/NppExec/src/NppExec.cpp#L2733
I recalled why I did not implement this before: I did not think that the result is worth the efforts. Really, running two loops (let's say N times for %PATH% and M times for %PATHEXT%) thus performing N*M checks for file existence - just to get the file's extension? Looks like shooting a fly with a cannon.
I think I'll add a manual option to be able to disable this behavior.

**Comment by d0vgan** [comment]
Implemented in https://github.com/d0vgan/nppexec/commits/develop .
A new advanced option "ChildProcess_RunPolicy" has been introduced to specify this behavior (see "NppExec_TechInfo.txt" for details).
Will be available in NppExec v0.6 RC3.

**Comment by Vyoam** [comment]
Thanks a ton, d0vgan. You're awesome.

Though, I built from the develop branch and deployed the dll to Plugins, along with setting ChildProcess_RunPolicy to 1 in C:\Program Files\Notepad++\plugins\doc\NppExec\NppExec_TechInfo.txt.
But, the updates seem not to be there and I still need to specify .bat extension.
Is it supposed to work through such a deployment? What could I be missing?

**Comment by vdovgan-clgx** [comment]
At the top of the file "NppExec_TechInfo.txt", it is written:
>  NppExec has advanced "hidden" settings which can be set manually.
>  You need to edit NppExec's ini-file: "\Plugins\Config\NppExec.ini".

And below:

> You can add specified keys to [Console] or [Options] section of this ini-file.

In our case we are talking about "ChildProcess_RunPolicy" under the section [Console].

**Comment by Vyoam** [comment]
Thanks.
It is working!!! :)
For reference, in Windows 10 the full path of the config file is C:\Users\<user>\AppData\Roaming\Notepad++\plugins\config\NppExec.ini

**Comment by d0vgan** [comment]
Implemented in NppExec v0.6 RC3.
