### ISSUE TITLE
Double clicking line in console output jumps to the first tab ocurrence if you have multiple tabs open with different files of the same name

### ISSUE THREAD

**Issue by mike406** [d0vgan/nppexec#90]
I use Notepad++ primarily for Python scripting and have been using NppExec to run `pylint.exe "$(FILE_NAME)"` on the file I am working on. I couple this with a console output filter set to `%FILE%:%LINE%:%CHAR%:*` which works well. I am able to double click on a line in the console output and it will jump my cursor to the line of code that is being referenced. However if I have two .py files open with the same name, even if they are from completely different projects and directories, NppExec will jump me to the tab of the file that is furthest to the left. Meaning if I have two projects open, both with a file "main.py", if I run pylint against the 2nd main.py and double click one of the lines in the console, Notepad++ will jump me to that line but in the first "main.py" tab. Is there a setting I am missing to avoid this behavior?

Edit:
I have limited experience with C++ but I traced the code to [this line](https://github.com/d0vgan/nppexec/blob/4cf31d9f433863285efaf357496efab14aa4619d/NppExec/src/DlgConsole.cpp#L3402C37-L3402C72). Something tells me there should be an additional check here where the current tab that is selected should be checked first prior to getting the first index encountered. Basically, NppExec should consider if the tab the user is currently looking at first is a match, before checking any others.

**Comment by d0vgan** [comment]
Yep, I see it. You are proposing to check the current (active) file first, right?
(I was additionally looking into the existing Notepad++'s messages to understand if it's possible to consider only files that belong to the current Project or Workspace - and I could not find such ability).

**Comment by mike406** [comment]
Yes that is correct. Alternatively, is it possible for NppExec to “remember” which file tab it ran against and use that instead?

**Comment by d0vgan** [comment]
You may try an automatic build of the latest development version, it is available here:
64-bit: https://ci.appveyor.com/project/d0vgan/nppexec/build/job/2tg78clnkqnc4usg/artifacts
32-bit: https://ci.appveyor.com/project/d0vgan/nppexec/build/job/a9csayxrwyjk7hah/artifacts

**Comment by mike406** [comment]
Thank you, the fix is working.
