### ISSUE TITLE
Notepad++ dev build NPP_OPEN fails

### ISSUE THREAD

**Issue by vinsworldcom** [d0vgan/nppexec#93]
I'm testing latest pre-release Notepad++ 64-bit dev builds and find an issue with this commit:

https://github.com/notepad-plus-plus/notepad-plus-plus/commit/bb278b26fc9a772242e702d2fac40c18c6cc21b9

Using the latest 8.8 NppExec, the `NPP_OPEN` command does not seem to work for me anymore.

On the previous Notepad++ 64-bit commit, using the `NPP_OPEN` command functions as expected - the file is opened in a Scintilla buffer.

**Comment by d0vgan** [comment]
Seems to be a mistake in Notepad++'s code for NPPM_RELOADFILE. Now it always return TRUE, whereas I was expecting it to return either TRUE on success or FALSE of failure.

According to "Notepad_plus_msgs.h", it should be either TRUE or FALSE:
~~~
#define NPPM_RELOADFILE (NPPMSG + 36)
	//BOOL NPPM_RELOADFILE(BOOL withAlert, TCHAR *filePathName2Reload)
~~~

**Comment by vinsworldcom** [comment]
Thanks for the quick diagnostic!

Shall I open a bug with Notepad++ then?

Cheers.

**Comment by d0vgan** [comment]
Yes, I think so.

**Comment by vinsworldcom** [comment]
Done:  https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14693

**Comment by vinsworldcom** [comment]
See:  https://github.com/notepad-plus-plus/notepad-plus-plus/pull/14708

Fix is coming
