### ISSUE TITLE
NppExec fails to open file in shellcheck.exe

### ISSUE THREAD

**Issue by 007revad** [d0vgan/nppexec#94]
**OS:** Windows 10 Pro 64-bit Version 22h2 (OS Build 19045.3570)
**Notepad++:** v8.6.8 (64-bit)
**NppExec:** 0.8.8

This Execute NppExec script command:
`C:\shellcheck\schellcheck.exe $(FULL_CURRENT_PATH)`

Results in in the NppExec Console showing:
```
C:\shellcheck\schellcheck.exe C:\shellcheck\syno_hdd_db.sh
; about to start a child process: "C:\shellcheck\schellcheck.exe C:\shellcheck\syno_hdd_db.sh"
CreateProcess() failed with error code 2:
The system cannot find the file specified.

================ READY ================
```
I can't tell if the file not found is shellcheck.exe or the file I have open in Notepad++

This Execute NppExec script command (with double quotes around $(FULL_CURRENT_PATH):
`C:\shellcheck\schellcheck.exe "$(FULL_CURRENT_PATH)"`

Results in in the NppExec Console showing:
```
C:\shellcheck\shellcheck.exe "C:\shellcheck\syno_hdd_db.sh”
Process started (PID=15972) >>>
C:\shellcheck\syno_hdd_db.shC:\shellcheck\syno_hdd_db.shshellcheck.exe: <stderr>: hPutChar: invalid argument (invalid character)
<<< Process finished (PID=15972). (Exit code 1)
================ READY ================
```
Exit code 1 does tell me anything that would indicate what the problem is.

**Comment by d0vgan** [comment]
I assume the shellcheck is the one from here:
https://github.com/koalaman/shellcheck/releases/tag/v0.10.0

With it, I have successfully run the NppExec's script
```
C:\ShellCheck\shellcheck.exe "$(FULL_CURRENT_PATH)"
```
against a random file "C:\msys64\usr\share\git\git-prompt.sh".

If you are using some custom build of shellcheck, you may need a prefix `cmd /C start /wait` as suggested by
 https://d0vgan.github.io/nppexec/?q=FAQ

**Comment by 007revad** [comment]
I am using https://github.com/koalaman/shellcheck/releases/tag/v0.10.0

I just found the problem. Somehow the last double quote was a curly double quote. I must have copied and pasted `$(FULL_CURRENT_PATH)”` from a webpage that used curly double quotes.
```
C:\shellcheck\shellcheck.exe "$(FULL_CURRENT_PATH)”
```
Thank you!
