### ISSUE TITLE
[Feature request] execute code cell

### ISSUE THREAD

**Issue by mrrezaie** [d0vgan/nppexec#96]
Hi, thanks for keep developing NppExec. 

It's common to have a cell of codes, for example in Python everything between `# %%` or `#%%` would be a cell. Here I have 3 cells:
```python
import os
print(os.getcwd())
# %%
import sys
print(sys.executable)
# %%
import numpy
print(numpy.__version__)
```

It would be great if you add a few options like:
- `Execute Cell` (select the texts of the current cell the cursor is located and execute it)
- `Execute Cell and Advance` (execute the current cell and put the cursor into the beginning of the next cell). 

This would make working with Npp and NppExec much easier and faster.

Thank you in advance.

**Comment by d0vgan** [comment]
I believe the following will be quite close to what you want:

1. Start python as a collateral process:
```
nppexec:: python -i -u
```
When a process is started as a collateral one (using the `nppexec::` prefix), this process will run in a separate thread, thus allowing to run additional NppExec's scripts and commands.

2. Run the following NppExec's script to select the text of the current cell and execute it by means of the running python:
```
npp_console local -

sci_sendmsg SCI_GETSELECTIONSTART
set local sel_start = $(MSG_RESULT)

sci_sendmsg SCI_GETSELECTIONEND
set local sel_end = $(MSG_RESULT)

if $(sel_start) == $(sel_end)
  sci_find NPE_SF_BACKWARD "# %%"
  set local cell_begin = $(MSG_RESULT)
  if $(cell_begin) == -1
    set local cell_begin = 0
  endif

  sci_find 0 "# %%"
  set local cell_end = $(MSG_RESULT)
  if $(cell_begin) == -1
    sci_sendmsg SCI_GETTEXTLENGTH
    set local cell_end = $(MSG_RESULT)
  endif

  sci_sendmsg SCI_SETSEL $(cell_begin) $(cell_end)
endif

npp_menucommand Plugins\NppExec\Execute Selected Text
```

**Comment by mrrezaie** [comment]
@d0vgan, I appreciate your help. This is so promising and impressive, works perfectly. Since this feature does not exist in the menu, most users are not aware of this.
