### ISSUE TITLE
It's not clear whether NppExec in executing or not

### ISSUE THREAD

**Issue by mrrezaie** [d0vgan/nppexec#99]
Hi, I'm using `Execute Selected Text` and sometimes the console freezes on a specific line for a while. At this moment, it's not clear whether NppExec is executing or available for the next command. 
I'm looking forward to improvements in this regard. Thanks for your time and effort.

**Comment by d0vgan** [comment]
Please provide more details. The example that causes a freeze, together with comments saying which exact line is freezing, would be great.

**Comment by mrrezaie** [comment]
Here is a dummy example; the test function takes 3s to be executed:
```python
from time import sleep

def test():
    sleep(3)

test()
test()
test()
```

This could be repeated n times. In the console, it's not easy to understand whether the execution has been finished or not. Is it possible to, for example, add a sign to the console title bar, or print something in the status bar when NppExec is executing? 

Hope I explain it properly.

**Comment by d0vgan** [comment]
When dealing with python by means of the NppExec's script mentioned in the https://github.com/d0vgan/nppexec/issues/96 ,
it is possible to do the following trick:

replace the 
```
npp_menucommand Plugins\NppExec\Execute Selected Text
```

with the following:
```
// npp_menucommand Plugins\NppExec\Execute Selected Text
set local LF ~ chr 0x0A
set local python_program = $(SELECTED_TEXT)$(LF)print('\n======== READY ========')
npp_exectext 0 $(python_program)
```

In this case, the text `======== READY ========` will be printed at the end of each python's code execution.

**Comment by mrrezaie** [comment]
Thanks, it's a nice workaround.
